<?php
/**
 * Auto generated from define_2.proto at 2023-02-13 12:39:22
 */

namespace Xnhd\Core\Pb\Sdo {
/**
 * ItemType enum
 */
final class ItemType
{
    const enmItemType_Invalid = 0;
    const enmItemGender_Boy = 268435456;
    const enmItemGender_Girl = 536870912;
    const enmItemGender_Common = 805306368;
    const enmItemGender_Mask = 805306368;
    const enmItemField_Player = 1048576;
    const enmItemField_Pet = 2097152;
    const enmItemField_Props = 3145728;
    const enmItemField_Game = 4194304;
    const enmItemField_House = 5242880;
    const enmItemField_Town = 6291456;
    const enmItemField_Merge = 7340032;
    const enmItemField_Plan = 8388608;
    const enmItemField_Mask = 267386880;
    const enmItemMainType_Mask = 983040;
    const enmItemPlayerPetType_Cloth = 65536;
    const enmItemPlayerPetType_Beauty = 131072;
    const enmItemPlayerPetType_Luxury = 196608;
    const enmItemPlayerPetType_Paint = 262144;
    const enmItemPropsType_Box = 65536;
    const enmItemPropsType_Buf = 131072;
    const enmItemPropsType_Att = 196608;
    const enmItemPropsType_Bill = 262144;
    const enmItemPropsType_Mate = 327680;
    const enmItemPropsType_Cost = 393216;
    const enmItemPropsType_Act = 458752;
    const enmItemPropsType_Gift = 524288;
    const enmItemPropsType_Ticket = 589824;
    const enmItemPropsType_Pet = 655360;
    const enmItemGameType_Title = 65536;
    const enmItemGameType_Asset = 131072;
    const enmItemGameType_Props = 196608;
    const enmItemGameType_Mater = 262144;
    const enmItemGameType_Head = 327680;
    const enmItemGameType_Effect = 393216;
    const enmItemGameType_Seed = 458752;
    const enmItemGameType_Unlock = 524288;
    const enmItemHouse_Furniture = 65536;
    const enmItemHouse_Fixtures = 131072;
    const enmItemHouse_Environment = 196608;
    const enmItemHouse_Function = 262144;
    const enmItemHouse_Building = 327680;
    const enmItemTown_Build = 65536;
    const enmItemTown_Layout = 131072;
    const enmItemTown_Addition = 196608;
    const enmItemMerge_Asset = 65536;
    const enmItemMerge_House = 131072;
    const enmItemPlan_Cloth = 65536;
    const enmItemPlan_Beauty = 131072;
    const enmItemPlan_Luxury = 196608;
    const enmItemPlan_House = 393216;
    const enmItemSubType_Mask = 65280;
    const enmItemClothSubType_Hair = 256;
    const enmItemClothSubType_Jacket = 512;
    const enmItemClothSubType_Pant = 768;
    const enmItemClothSubType_Shoes = 1024;
    const enmItemClothSubType_X = 1280;
    const enmItemClothSubType_Hand = 1536;
    const enmItemBeautySubType_Face = 256;
    const enmItemBeautySubType_Exp = 512;
    const enmItemBeautySubType_Top = 768;
    const enmItemBeautySubType_Glass = 1024;
    const enmItemBeautySubType_Mouth = 1280;
    const enmItemBeautySubType_Ear = 1536;
    const enmItemBeautySubType_Necklace = 1792;
    const enmItemBeautySubType_Mask = 2048;
    const enmItemBeautySubType_LHand = 2304;
    const enmItemBeautySubType_RHand = 2560;
    const enmItemBeautySubType_TwoHands = 2816;
    const enmItemBeautySubType_LWrist = 3072;
    const enmItemBeautySubType_RWrist = 3328;
    const enmItemBeautySubType_TwoWrists = 3584;
    const enmItemBeautySubType_Body = 3840;
    const enmItemBeautySubType_Back = 4096;
    const enmItemBeautySubType_Tail = 4352;
    const enmItemBeautySubType_Glove = 4608;
    const enmItemBeautySubType_Bea = 4864;
    const enmItemLuxurySubType_Shaw = 5120;
    const enmItemLuxurySubType_LShoulder = 256;
    const enmItemLuxurySubType_RShoulder = 512;
    const enmItemLuxurySubType_TwoShoulder = 768;
    const enmItemLuxurySubType_LLeg = 1024;
    const enmItemLuxurySubType_RLeg = 1280;
    const enmItemLuxurySubType_TwoLegs = 1536;
    const enmItemLuxurySubType_Ring = 1792;
    const enmItemLuxurySubType_Wing = 2048;
    const enmItemLuxurySubType_Cloak = 2304;
    const enmItemLuxurySubType_Seat = 2560;
    const enmItemLuxurySubType_Plane = 2816;
    const enmItemLuxurySubType_Pig = 3072;
    const enmItemLuxurySubType_Groud = 3328;
    const enmItemLuxurySubType_Pet = 3584;
    const enmItemLuxurySubType_FootPrint = 3840;
    const enmItemLuxurySubType_LStr = 4096;
    const enmItemLuxurySubType_RStr = 4352;
    const enmItemLuxurySubType_TwoStr = 4608;
    const enmItemLuxurySubType_PoolPlan = 4864;
    const enmItemPaintSubType_Pupil = 256;
    const enmItemPaintSubType_EyeBrow = 512;
    const enmItemPaintSubType_EyeShadow = 768;
    const enmItemPaintSubType_Eyelash = 1024;
    const enmItemPaintSubType_Eyeliner = 1280;
    const enmItemPaintSubType_Lip = 1536;
    const enmItemPaintSubType_Cheek = 1792;
    const enmItemPaintSubType_Tattoo = 2048;
    const enmItemPaintSubType_Eyelids = 2304;
    const enmItemPaintSubType_Skin = 2560;
    const enmItemPropsBoxSubType_Fixed = 256;
    const enmItemPropsBoxSubType_Select = 512;
    const enmItemPropsBoxSubType_Rand = 768;
    const enmItemPropsBoxSubType_Acc = 1024;
    const enmItemPropsBoxSubType_Suit = 1280;
    const enmItemPropsBoxSubType_Lover = 1536;
    const enmItemPropsBoxSubType_Blind = 1792;
    const enmItemPropsBoxSubType_Raffle = 2048;
    const enmItemPropsBufSubType_Exp = 256;
    const enmItemPropsBufSubType_GCoin = 512;
    const enmItemPropsBufSubType_Task = 768;
    const enmItemPropsBufSubType_Heart = 1024;
    const enmItemPropsBufSubType_Par = 1280;
    const enmItemPropsBufSubType_Tf = 1536;
    const enmItemPropsBufSubType_Comm = 1792;
    const enmItemPropsBufSubType_Bub = 2048;
    const enmItemPropsBufSubType_Silk = 2304;
    const enmItemPropsBufSubType_Doll = 2560;
    const enmItemPropsAttSubType_Money = 256;
    const enmItemPropsAttSubType_Score = 512;
    const enmItemPropsAttSubType_GCoin = 768;
    const enmItemPropsAttSubType_GWealth = 1024;
    const enmItemPropsAttSubType_Exp = 1280;
    const enmItemPropsAttSubType_Level = 1536;
    const enmItemPropsAttSubType_Achieve = 1792;
    const enmItemPropsAttSubType_Stamina = 2048;
    const enmItemPropsAttSubType_BP = 2304;
    const enmItemPropsAttSubType_Heart = 2560;
    const enmItemPropsAttSubType_Bag = 2816;
    const enmItemPropsAttSubType_Soul = 3072;
    const enmItemPropsBillSubType_Common = 256;
    const enmItemPropsBillSubType_SSpk = 512;
    const enmItemPropsBillSubType_BSpk = 768;
    const enmItemPropsBillSubType_ZSpk = 1024;
    const enmItemPropsBillSubType_USpk = 1280;
    const enmItemPropsBillSubType_LSSpk = 1536;
    const enmItemPropsBillSubType_LBSpk = 1792;
    const enmItemPropsBillSubType_Act = 2048;
    const enmItemPropsBillSubType_Eff = 2560;
    const enmItemPropsBillSubType_Game = 2816;
    const enmItemPropsBillSubType_Dinner = 3072;
    const enmItemPropsTicketSubType_Discount = 256;
    const enmItemPropsTicketSubType_FullCut = 512;
    const enmItemPropsTicketSubType_Coupon = 768;
    const enmItemPropsPetSubType_Egg = 256;
    const enmItemPropsPetSubType_Food = 512;
    const enmItemPropsPetSubType_Clip = 768;
    const enmItemPropsPetSubType_UpGradeCharm = 1024;
    const enmItemPropsPetSubType_Exchange = 1280;
    const enmItemPropsPetSubType_PhysicalMedicine = 1536;
    const enmItemPropsPetSubType_MoodMedicine = 1792;
    const enmItemPropsPetSubType_Other = 2048;
    const enmItemPropsPetSubType_Pet = 2304;
    const enmItemPropsActSubType_Common = 256;
    const enmItemPropsActSubType_BP = 512;
    const enmItemPropsActSubType_Money = 768;
    const enmItemPropsGiftSubType_Friend = 256;
    const enmItemPropsGiftSubType_Love = 512;
    const enmItemPropsCostSubType_Theme = 256;
    const enmItemPropsCostSubType_Couple = 512;
    const enmItemPropsCostSubType_SNS = 768;
    const enmItemPropsCostSubType_Qualify = 1024;
    const enmItemPropsCostSubType_Guild = 1280;
    const enmItemPropsCostSubType_Raffle = 1536;
    const enmItemPropsCostSubType_Measure = 1792;
    const enmItemPropsMateSubType_Common = 256;
    const enmItemPropsMateSubType_Act = 512;
    const enmItemPropsMateSubType_SNS = 768;
    const enmItemPropsMateSubType_Guild = 1024;
    const enmItemPropsMateSubType_Raffle = 1280;
    const enmItemPropsMateSubType_Couple = 1536;
    const enmItemPropsMateSubType_Wedding = 1792;
    const enmItemPropsMateSubType_Qualify = 2048;
    const enmItemPropsMateSubType_Cost = 2304;
    const enmItemGameTitleSubType_Green = 256;
    const enmItemGameTitleSubType_Blue = 512;
    const enmItemGameTitleSubType_Purple = 768;
    const enmItemGameTitleSubType_Orange = 1024;
    const enmItemGameTitleSubType_Red = 1280;
    const enmItemGameAssetSubType_Money = 256;
    const enmItemGameAssetSubType_Score = 512;
    const enmItemGameAssetSubType_GCoin = 768;
    const enmItemGameAssetSubType_Stamina = 1024;
    const enmItemGameAssetSubType_Exp = 1280;
    const enmItemGameAssetSubType_Level = 1536;
    const enmItemGameAssetSubType_QCoin = 1792;
    const enmItemGameAssetSubType_HCoin = 2048;
    const enmItemGameAssetSubType_Achieve = 2304;
    const enmItemGameAssetSubType_Couple = 2560;
    const enmItemGameAssetSubType_GHonour = 2816;
    const enmItemGameAssetSubType_SpendCoin = 3072;
    const enmItemGamePropsSubType_Activity = 256;
    const enmItemGamePropsSubType_Qualify = 512;
    const enmItemGamePropsSubType_House = 768;
    const enmItemGamePropsSubType_Player = 1024;
    const enmItemGamePropsSubType_BP = 1280;
    const enmItemGamePropsSubType_Tour = 1536;
    const enmItemGamePropsSubType_Guild = 1792;
    const enmItemGamePropsSubType_Couple = 2048;
    const enmItemGameMedalSubType_Guild = 256;
    const enmItemGameMatSubType_Rankup = 256;
    const enmItemGameMatSubType_Chip = 512;
    const enmItemGameMatSubType_Task = 768;
    const enmItemGameMatSubType_Guild = 1024;
    const enmItemGameMatSubType_Make = 1280;
    const enmItemGameMatSubType_Color = 1536;
    const enmItemGameMatSubType_Advance = 1792;
    const enmItemGameMatSubType_House = 2048;
    const enmItemGameMatSubType_Town = 2304;
    const enmItemGameEffectSubType_Cloth = 256;
    const enmItemGameSeedSubType_Cloth = 256;
    const enmItemGameSeedSubType_Pasture = 512;
    const enmItemGameUnlockSubType_Action = 256;
    const enmItemGameUnlockSubType_Swim = 512;
    const enmItemGameUnlockSubType_Pose = 768;
    const enmHouseFurnitureSubType_Big = 256;
    const enmHouseFurnitureSubType_Small = 512;
    const enmHouseFurnitureSubType_Table = 768;
    const enmHouseFurnitureSubType_Box = 1024;
    const enmHouseFurnitureSubType_Widgets = 1280;
    const enmHouseFurnitureSubType_Carpet = 1536;
    const enmHouseFurnitureSubType_Special = 1792;
    const enmHouseFixturesSubType_Floor = 256;
    const enmHouseFixturesSubType_Wall = 512;
    const enmHouseFixturesSubType_Door = 768;
    const enmHouseFixturesSubType_Window = 1024;
    const enmHouseFixturesSubType_Curtains = 1280;
    const enmHouseFixturesSubType_Ladder = 1536;
    const enmHouseEnvironSubType_Sky = 256;
    const enmHouseFuctionSubType_Born = 256;
    const enmHouseFuctionSubType_Cloth = 512;
    const enmHouseFuctionSubType_Achieve = 768;
    const enmHouseFuctionSubType_Photo = 1024;
    const enmHouseBuildingSubType_House = 1280;
    const enmTownBuildSubType_House = 256;
    const enmTownBuildSubType_Cabin = 512;
    const enmTownBuildSubType_Produce = 768;
    const enmTownLayoutSubType_Road = 256;
    const enmTownLayoutSubType_Fence = 512;
    const enmTownLayoutSubType_Water = 768;
    const enmTownAdditionSubType_Decorate = 256;
    const enmTownAdditionSubType_Landscape = 512;
    const enmMergeAssetSubType_Coin = 256;
    const enmMergeAssetSubType_Exp = 512;
    const enmMergeAssetSubType_Stamina = 768;
    const enmMergeAssetSubType_Score = 1024;
    const enmMergeHouseSubType_Box = 256;
    const enmMergeHouseSubType_Element = 512;
    const enmMergeHouseSubType_Plan = 768;
    const enmMergeHouseSubType_BoxNotPutBack = 1024;
    const enmItemExtraType_Mask = 255;
    const enmItemPropsBillWedExtraType_Card = 1;
    const enmItemPropsBillWedExtraType_Stage = 2;
    const enmItemPropsBillWedExtraType_Cloth = 3;
    const enmItemPropsBillWedExtraType_Ring = 4;
    const enmTownProduceExtraType_Farm = 1;
    const enmTownProduceExtraType_Pasture = 2;
    const enmTownProduceExtraType_Well = 3;
    const enmTownProduceExtraType_Color = 4;
    const enmTownProduceExtraType_Cloth = 5;
    const enmTownProduceExtraType_Material = 6;
    const enmTownProduceExtraType_Food = 7;
    const enmItemPropsActBPExtraType_Exchange = 1;
    const enmItemPropsActBPExtraType_TaskCard = 2;
    const enmItemPropsActMoneyExtraType_Puzzle = 1;
    const enmItemGamePropsBPExtraType_Exp = 1;
    const enmItemGamePropsBPExtraType_ActiveLimit = 2;
    const enmItemGamePropsBPExtraType_Purchase = 3;
    const enmItemGamePropsBPExtraType_Level = 4;
    const enmItemGamePropsBPExtraType_Active = 5;
    const enmItemGamePropsTourExtraType_TreeKey = 1;
    const enmItemGamePropsTourExtraType_Part = 2;
    const enmItemPropsBoxExtraType_Wish = 1;
    const enmItemPropsBoxExtraType_Hide = 2;
    const enmItemGamePropsCoupleExtraType_Exp = 1;
    const enmItemGamePropsCoupleExtraType_Love = 2;
    const enmItemGamePropsCoupleExtraType_Purchase = 3;
    const enmItemGamePropsCoupleExtraType_PetHouse = 4;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'enmItemType_Invalid' => self::enmItemType_Invalid,
            'enmItemGender_Boy' => self::enmItemGender_Boy,
            'enmItemGender_Girl' => self::enmItemGender_Girl,
            'enmItemGender_Common' => self::enmItemGender_Common,
            'enmItemGender_Mask' => self::enmItemGender_Mask,
            'enmItemField_Player' => self::enmItemField_Player,
            'enmItemField_Pet' => self::enmItemField_Pet,
            'enmItemField_Props' => self::enmItemField_Props,
            'enmItemField_Game' => self::enmItemField_Game,
            'enmItemField_House' => self::enmItemField_House,
            'enmItemField_Town' => self::enmItemField_Town,
            'enmItemField_Merge' => self::enmItemField_Merge,
            'enmItemField_Plan' => self::enmItemField_Plan,
            'enmItemField_Mask' => self::enmItemField_Mask,
            'enmItemMainType_Mask' => self::enmItemMainType_Mask,
            'enmItemPlayerPetType_Cloth' => self::enmItemPlayerPetType_Cloth,
            'enmItemPlayerPetType_Beauty' => self::enmItemPlayerPetType_Beauty,
            'enmItemPlayerPetType_Luxury' => self::enmItemPlayerPetType_Luxury,
            'enmItemPlayerPetType_Paint' => self::enmItemPlayerPetType_Paint,
            'enmItemPropsType_Box' => self::enmItemPropsType_Box,
            'enmItemPropsType_Buf' => self::enmItemPropsType_Buf,
            'enmItemPropsType_Att' => self::enmItemPropsType_Att,
            'enmItemPropsType_Bill' => self::enmItemPropsType_Bill,
            'enmItemPropsType_Mate' => self::enmItemPropsType_Mate,
            'enmItemPropsType_Cost' => self::enmItemPropsType_Cost,
            'enmItemPropsType_Act' => self::enmItemPropsType_Act,
            'enmItemPropsType_Gift' => self::enmItemPropsType_Gift,
            'enmItemPropsType_Ticket' => self::enmItemPropsType_Ticket,
            'enmItemPropsType_Pet' => self::enmItemPropsType_Pet,
            'enmItemGameType_Title' => self::enmItemGameType_Title,
            'enmItemGameType_Asset' => self::enmItemGameType_Asset,
            'enmItemGameType_Props' => self::enmItemGameType_Props,
            'enmItemGameType_Mater' => self::enmItemGameType_Mater,
            'enmItemGameType_Head' => self::enmItemGameType_Head,
            'enmItemGameType_Effect' => self::enmItemGameType_Effect,
            'enmItemGameType_Seed' => self::enmItemGameType_Seed,
            'enmItemGameType_Unlock' => self::enmItemGameType_Unlock,
            'enmItemHouse_Furniture' => self::enmItemHouse_Furniture,
            'enmItemHouse_Fixtures' => self::enmItemHouse_Fixtures,
            'enmItemHouse_Environment' => self::enmItemHouse_Environment,
            'enmItemHouse_Function' => self::enmItemHouse_Function,
            'enmItemHouse_Building' => self::enmItemHouse_Building,
            'enmItemTown_Build' => self::enmItemTown_Build,
            'enmItemTown_Layout' => self::enmItemTown_Layout,
            'enmItemTown_Addition' => self::enmItemTown_Addition,
            'enmItemMerge_Asset' => self::enmItemMerge_Asset,
            'enmItemMerge_House' => self::enmItemMerge_House,
            'enmItemPlan_Cloth' => self::enmItemPlan_Cloth,
            'enmItemPlan_Beauty' => self::enmItemPlan_Beauty,
            'enmItemPlan_Luxury' => self::enmItemPlan_Luxury,
            'enmItemPlan_House' => self::enmItemPlan_House,
            'enmItemSubType_Mask' => self::enmItemSubType_Mask,
            'enmItemClothSubType_Hair' => self::enmItemClothSubType_Hair,
            'enmItemClothSubType_Jacket' => self::enmItemClothSubType_Jacket,
            'enmItemClothSubType_Pant' => self::enmItemClothSubType_Pant,
            'enmItemClothSubType_Shoes' => self::enmItemClothSubType_Shoes,
            'enmItemClothSubType_X' => self::enmItemClothSubType_X,
            'enmItemClothSubType_Hand' => self::enmItemClothSubType_Hand,
            'enmItemBeautySubType_Face' => self::enmItemBeautySubType_Face,
            'enmItemBeautySubType_Exp' => self::enmItemBeautySubType_Exp,
            'enmItemBeautySubType_Top' => self::enmItemBeautySubType_Top,
            'enmItemBeautySubType_Glass' => self::enmItemBeautySubType_Glass,
            'enmItemBeautySubType_Mouth' => self::enmItemBeautySubType_Mouth,
            'enmItemBeautySubType_Ear' => self::enmItemBeautySubType_Ear,
            'enmItemBeautySubType_Necklace' => self::enmItemBeautySubType_Necklace,
            'enmItemBeautySubType_Mask' => self::enmItemBeautySubType_Mask,
            'enmItemBeautySubType_LHand' => self::enmItemBeautySubType_LHand,
            'enmItemBeautySubType_RHand' => self::enmItemBeautySubType_RHand,
            'enmItemBeautySubType_TwoHands' => self::enmItemBeautySubType_TwoHands,
            'enmItemBeautySubType_LWrist' => self::enmItemBeautySubType_LWrist,
            'enmItemBeautySubType_RWrist' => self::enmItemBeautySubType_RWrist,
            'enmItemBeautySubType_TwoWrists' => self::enmItemBeautySubType_TwoWrists,
            'enmItemBeautySubType_Body' => self::enmItemBeautySubType_Body,
            'enmItemBeautySubType_Back' => self::enmItemBeautySubType_Back,
            'enmItemBeautySubType_Tail' => self::enmItemBeautySubType_Tail,
            'enmItemBeautySubType_Glove' => self::enmItemBeautySubType_Glove,
            'enmItemBeautySubType_Bea' => self::enmItemBeautySubType_Bea,
            'enmItemLuxurySubType_Shaw' => self::enmItemLuxurySubType_Shaw,
            'enmItemLuxurySubType_LShoulder' => self::enmItemLuxurySubType_LShoulder,
            'enmItemLuxurySubType_RShoulder' => self::enmItemLuxurySubType_RShoulder,
            'enmItemLuxurySubType_TwoShoulder' => self::enmItemLuxurySubType_TwoShoulder,
            'enmItemLuxurySubType_LLeg' => self::enmItemLuxurySubType_LLeg,
            'enmItemLuxurySubType_RLeg' => self::enmItemLuxurySubType_RLeg,
            'enmItemLuxurySubType_TwoLegs' => self::enmItemLuxurySubType_TwoLegs,
            'enmItemLuxurySubType_Ring' => self::enmItemLuxurySubType_Ring,
            'enmItemLuxurySubType_Wing' => self::enmItemLuxurySubType_Wing,
            'enmItemLuxurySubType_Cloak' => self::enmItemLuxurySubType_Cloak,
            'enmItemLuxurySubType_Seat' => self::enmItemLuxurySubType_Seat,
            'enmItemLuxurySubType_Plane' => self::enmItemLuxurySubType_Plane,
            'enmItemLuxurySubType_Pig' => self::enmItemLuxurySubType_Pig,
            'enmItemLuxurySubType_Groud' => self::enmItemLuxurySubType_Groud,
            'enmItemLuxurySubType_Pet' => self::enmItemLuxurySubType_Pet,
            'enmItemLuxurySubType_FootPrint' => self::enmItemLuxurySubType_FootPrint,
            'enmItemLuxurySubType_LStr' => self::enmItemLuxurySubType_LStr,
            'enmItemLuxurySubType_RStr' => self::enmItemLuxurySubType_RStr,
            'enmItemLuxurySubType_TwoStr' => self::enmItemLuxurySubType_TwoStr,
            'enmItemLuxurySubType_PoolPlan' => self::enmItemLuxurySubType_PoolPlan,
            'enmItemPaintSubType_Pupil' => self::enmItemPaintSubType_Pupil,
            'enmItemPaintSubType_EyeBrow' => self::enmItemPaintSubType_EyeBrow,
            'enmItemPaintSubType_EyeShadow' => self::enmItemPaintSubType_EyeShadow,
            'enmItemPaintSubType_Eyelash' => self::enmItemPaintSubType_Eyelash,
            'enmItemPaintSubType_Eyeliner' => self::enmItemPaintSubType_Eyeliner,
            'enmItemPaintSubType_Lip' => self::enmItemPaintSubType_Lip,
            'enmItemPaintSubType_Cheek' => self::enmItemPaintSubType_Cheek,
            'enmItemPaintSubType_Tattoo' => self::enmItemPaintSubType_Tattoo,
            'enmItemPaintSubType_Eyelids' => self::enmItemPaintSubType_Eyelids,
            'enmItemPaintSubType_Skin' => self::enmItemPaintSubType_Skin,
            'enmItemPropsBoxSubType_Fixed' => self::enmItemPropsBoxSubType_Fixed,
            'enmItemPropsBoxSubType_Select' => self::enmItemPropsBoxSubType_Select,
            'enmItemPropsBoxSubType_Rand' => self::enmItemPropsBoxSubType_Rand,
            'enmItemPropsBoxSubType_Acc' => self::enmItemPropsBoxSubType_Acc,
            'enmItemPropsBoxSubType_Suit' => self::enmItemPropsBoxSubType_Suit,
            'enmItemPropsBoxSubType_Lover' => self::enmItemPropsBoxSubType_Lover,
            'enmItemPropsBoxSubType_Blind' => self::enmItemPropsBoxSubType_Blind,
            'enmItemPropsBoxSubType_Raffle' => self::enmItemPropsBoxSubType_Raffle,
            'enmItemPropsBufSubType_Exp' => self::enmItemPropsBufSubType_Exp,
            'enmItemPropsBufSubType_GCoin' => self::enmItemPropsBufSubType_GCoin,
            'enmItemPropsBufSubType_Task' => self::enmItemPropsBufSubType_Task,
            'enmItemPropsBufSubType_Heart' => self::enmItemPropsBufSubType_Heart,
            'enmItemPropsBufSubType_Par' => self::enmItemPropsBufSubType_Par,
            'enmItemPropsBufSubType_Tf' => self::enmItemPropsBufSubType_Tf,
            'enmItemPropsBufSubType_Comm' => self::enmItemPropsBufSubType_Comm,
            'enmItemPropsBufSubType_Bub' => self::enmItemPropsBufSubType_Bub,
            'enmItemPropsBufSubType_Silk' => self::enmItemPropsBufSubType_Silk,
            'enmItemPropsBufSubType_Doll' => self::enmItemPropsBufSubType_Doll,
            'enmItemPropsAttSubType_Money' => self::enmItemPropsAttSubType_Money,
            'enmItemPropsAttSubType_Score' => self::enmItemPropsAttSubType_Score,
            'enmItemPropsAttSubType_GCoin' => self::enmItemPropsAttSubType_GCoin,
            'enmItemPropsAttSubType_GWealth' => self::enmItemPropsAttSubType_GWealth,
            'enmItemPropsAttSubType_Exp' => self::enmItemPropsAttSubType_Exp,
            'enmItemPropsAttSubType_Level' => self::enmItemPropsAttSubType_Level,
            'enmItemPropsAttSubType_Achieve' => self::enmItemPropsAttSubType_Achieve,
            'enmItemPropsAttSubType_Stamina' => self::enmItemPropsAttSubType_Stamina,
            'enmItemPropsAttSubType_BP' => self::enmItemPropsAttSubType_BP,
            'enmItemPropsAttSubType_Heart' => self::enmItemPropsAttSubType_Heart,
            'enmItemPropsAttSubType_Bag' => self::enmItemPropsAttSubType_Bag,
            'enmItemPropsAttSubType_Soul' => self::enmItemPropsAttSubType_Soul,
            'enmItemPropsBillSubType_Common' => self::enmItemPropsBillSubType_Common,
            'enmItemPropsBillSubType_SSpk' => self::enmItemPropsBillSubType_SSpk,
            'enmItemPropsBillSubType_BSpk' => self::enmItemPropsBillSubType_BSpk,
            'enmItemPropsBillSubType_ZSpk' => self::enmItemPropsBillSubType_ZSpk,
            'enmItemPropsBillSubType_USpk' => self::enmItemPropsBillSubType_USpk,
            'enmItemPropsBillSubType_LSSpk' => self::enmItemPropsBillSubType_LSSpk,
            'enmItemPropsBillSubType_LBSpk' => self::enmItemPropsBillSubType_LBSpk,
            'enmItemPropsBillSubType_Act' => self::enmItemPropsBillSubType_Act,
            'enmItemPropsBillSubType_Eff' => self::enmItemPropsBillSubType_Eff,
            'enmItemPropsBillSubType_Game' => self::enmItemPropsBillSubType_Game,
            'enmItemPropsBillSubType_Dinner' => self::enmItemPropsBillSubType_Dinner,
            'enmItemPropsTicketSubType_Discount' => self::enmItemPropsTicketSubType_Discount,
            'enmItemPropsTicketSubType_FullCut' => self::enmItemPropsTicketSubType_FullCut,
            'enmItemPropsTicketSubType_Coupon' => self::enmItemPropsTicketSubType_Coupon,
            'enmItemPropsPetSubType_Egg' => self::enmItemPropsPetSubType_Egg,
            'enmItemPropsPetSubType_Food' => self::enmItemPropsPetSubType_Food,
            'enmItemPropsPetSubType_Clip' => self::enmItemPropsPetSubType_Clip,
            'enmItemPropsPetSubType_UpGradeCharm' => self::enmItemPropsPetSubType_UpGradeCharm,
            'enmItemPropsPetSubType_Exchange' => self::enmItemPropsPetSubType_Exchange,
            'enmItemPropsPetSubType_PhysicalMedicine' => self::enmItemPropsPetSubType_PhysicalMedicine,
            'enmItemPropsPetSubType_MoodMedicine' => self::enmItemPropsPetSubType_MoodMedicine,
            'enmItemPropsPetSubType_Other' => self::enmItemPropsPetSubType_Other,
            'enmItemPropsPetSubType_Pet' => self::enmItemPropsPetSubType_Pet,
            'enmItemPropsActSubType_Common' => self::enmItemPropsActSubType_Common,
            'enmItemPropsActSubType_BP' => self::enmItemPropsActSubType_BP,
            'enmItemPropsActSubType_Money' => self::enmItemPropsActSubType_Money,
            'enmItemPropsGiftSubType_Friend' => self::enmItemPropsGiftSubType_Friend,
            'enmItemPropsGiftSubType_Love' => self::enmItemPropsGiftSubType_Love,
            'enmItemPropsCostSubType_Theme' => self::enmItemPropsCostSubType_Theme,
            'enmItemPropsCostSubType_Couple' => self::enmItemPropsCostSubType_Couple,
            'enmItemPropsCostSubType_SNS' => self::enmItemPropsCostSubType_SNS,
            'enmItemPropsCostSubType_Qualify' => self::enmItemPropsCostSubType_Qualify,
            'enmItemPropsCostSubType_Guild' => self::enmItemPropsCostSubType_Guild,
            'enmItemPropsCostSubType_Raffle' => self::enmItemPropsCostSubType_Raffle,
            'enmItemPropsCostSubType_Measure' => self::enmItemPropsCostSubType_Measure,
            'enmItemPropsMateSubType_Common' => self::enmItemPropsMateSubType_Common,
            'enmItemPropsMateSubType_Act' => self::enmItemPropsMateSubType_Act,
            'enmItemPropsMateSubType_SNS' => self::enmItemPropsMateSubType_SNS,
            'enmItemPropsMateSubType_Guild' => self::enmItemPropsMateSubType_Guild,
            'enmItemPropsMateSubType_Raffle' => self::enmItemPropsMateSubType_Raffle,
            'enmItemPropsMateSubType_Couple' => self::enmItemPropsMateSubType_Couple,
            'enmItemPropsMateSubType_Wedding' => self::enmItemPropsMateSubType_Wedding,
            'enmItemPropsMateSubType_Qualify' => self::enmItemPropsMateSubType_Qualify,
            'enmItemPropsMateSubType_Cost' => self::enmItemPropsMateSubType_Cost,
            'enmItemGameTitleSubType_Green' => self::enmItemGameTitleSubType_Green,
            'enmItemGameTitleSubType_Blue' => self::enmItemGameTitleSubType_Blue,
            'enmItemGameTitleSubType_Purple' => self::enmItemGameTitleSubType_Purple,
            'enmItemGameTitleSubType_Orange' => self::enmItemGameTitleSubType_Orange,
            'enmItemGameTitleSubType_Red' => self::enmItemGameTitleSubType_Red,
            'enmItemGameAssetSubType_Money' => self::enmItemGameAssetSubType_Money,
            'enmItemGameAssetSubType_Score' => self::enmItemGameAssetSubType_Score,
            'enmItemGameAssetSubType_GCoin' => self::enmItemGameAssetSubType_GCoin,
            'enmItemGameAssetSubType_Stamina' => self::enmItemGameAssetSubType_Stamina,
            'enmItemGameAssetSubType_Exp' => self::enmItemGameAssetSubType_Exp,
            'enmItemGameAssetSubType_Level' => self::enmItemGameAssetSubType_Level,
            'enmItemGameAssetSubType_QCoin' => self::enmItemGameAssetSubType_QCoin,
            'enmItemGameAssetSubType_HCoin' => self::enmItemGameAssetSubType_HCoin,
            'enmItemGameAssetSubType_Achieve' => self::enmItemGameAssetSubType_Achieve,
            'enmItemGameAssetSubType_Couple' => self::enmItemGameAssetSubType_Couple,
            'enmItemGameAssetSubType_GHonour' => self::enmItemGameAssetSubType_GHonour,
            'enmItemGameAssetSubType_SpendCoin' => self::enmItemGameAssetSubType_SpendCoin,
            'enmItemGamePropsSubType_Activity' => self::enmItemGamePropsSubType_Activity,
            'enmItemGamePropsSubType_Qualify' => self::enmItemGamePropsSubType_Qualify,
            'enmItemGamePropsSubType_House' => self::enmItemGamePropsSubType_House,
            'enmItemGamePropsSubType_Player' => self::enmItemGamePropsSubType_Player,
            'enmItemGamePropsSubType_BP' => self::enmItemGamePropsSubType_BP,
            'enmItemGamePropsSubType_Tour' => self::enmItemGamePropsSubType_Tour,
            'enmItemGamePropsSubType_Guild' => self::enmItemGamePropsSubType_Guild,
            'enmItemGamePropsSubType_Couple' => self::enmItemGamePropsSubType_Couple,
            'enmItemGameMedalSubType_Guild' => self::enmItemGameMedalSubType_Guild,
            'enmItemGameMatSubType_Rankup' => self::enmItemGameMatSubType_Rankup,
            'enmItemGameMatSubType_Chip' => self::enmItemGameMatSubType_Chip,
            'enmItemGameMatSubType_Task' => self::enmItemGameMatSubType_Task,
            'enmItemGameMatSubType_Guild' => self::enmItemGameMatSubType_Guild,
            'enmItemGameMatSubType_Make' => self::enmItemGameMatSubType_Make,
            'enmItemGameMatSubType_Color' => self::enmItemGameMatSubType_Color,
            'enmItemGameMatSubType_Advance' => self::enmItemGameMatSubType_Advance,
            'enmItemGameMatSubType_House' => self::enmItemGameMatSubType_House,
            'enmItemGameMatSubType_Town' => self::enmItemGameMatSubType_Town,
            'enmItemGameEffectSubType_Cloth' => self::enmItemGameEffectSubType_Cloth,
            'enmItemGameSeedSubType_Cloth' => self::enmItemGameSeedSubType_Cloth,
            'enmItemGameSeedSubType_Pasture' => self::enmItemGameSeedSubType_Pasture,
            'enmItemGameUnlockSubType_Action' => self::enmItemGameUnlockSubType_Action,
            'enmItemGameUnlockSubType_Swim' => self::enmItemGameUnlockSubType_Swim,
            'enmItemGameUnlockSubType_Pose' => self::enmItemGameUnlockSubType_Pose,
            'enmHouseFurnitureSubType_Big' => self::enmHouseFurnitureSubType_Big,
            'enmHouseFurnitureSubType_Small' => self::enmHouseFurnitureSubType_Small,
            'enmHouseFurnitureSubType_Table' => self::enmHouseFurnitureSubType_Table,
            'enmHouseFurnitureSubType_Box' => self::enmHouseFurnitureSubType_Box,
            'enmHouseFurnitureSubType_Widgets' => self::enmHouseFurnitureSubType_Widgets,
            'enmHouseFurnitureSubType_Carpet' => self::enmHouseFurnitureSubType_Carpet,
            'enmHouseFurnitureSubType_Special' => self::enmHouseFurnitureSubType_Special,
            'enmHouseFixturesSubType_Floor' => self::enmHouseFixturesSubType_Floor,
            'enmHouseFixturesSubType_Wall' => self::enmHouseFixturesSubType_Wall,
            'enmHouseFixturesSubType_Door' => self::enmHouseFixturesSubType_Door,
            'enmHouseFixturesSubType_Window' => self::enmHouseFixturesSubType_Window,
            'enmHouseFixturesSubType_Curtains' => self::enmHouseFixturesSubType_Curtains,
            'enmHouseFixturesSubType_Ladder' => self::enmHouseFixturesSubType_Ladder,
            'enmHouseEnvironSubType_Sky' => self::enmHouseEnvironSubType_Sky,
            'enmHouseFuctionSubType_Born' => self::enmHouseFuctionSubType_Born,
            'enmHouseFuctionSubType_Cloth' => self::enmHouseFuctionSubType_Cloth,
            'enmHouseFuctionSubType_Achieve' => self::enmHouseFuctionSubType_Achieve,
            'enmHouseFuctionSubType_Photo' => self::enmHouseFuctionSubType_Photo,
            'enmHouseBuildingSubType_House' => self::enmHouseBuildingSubType_House,
            'enmTownBuildSubType_House' => self::enmTownBuildSubType_House,
            'enmTownBuildSubType_Cabin' => self::enmTownBuildSubType_Cabin,
            'enmTownBuildSubType_Produce' => self::enmTownBuildSubType_Produce,
            'enmTownLayoutSubType_Road' => self::enmTownLayoutSubType_Road,
            'enmTownLayoutSubType_Fence' => self::enmTownLayoutSubType_Fence,
            'enmTownLayoutSubType_Water' => self::enmTownLayoutSubType_Water,
            'enmTownAdditionSubType_Decorate' => self::enmTownAdditionSubType_Decorate,
            'enmTownAdditionSubType_Landscape' => self::enmTownAdditionSubType_Landscape,
            'enmMergeAssetSubType_Coin' => self::enmMergeAssetSubType_Coin,
            'enmMergeAssetSubType_Exp' => self::enmMergeAssetSubType_Exp,
            'enmMergeAssetSubType_Stamina' => self::enmMergeAssetSubType_Stamina,
            'enmMergeAssetSubType_Score' => self::enmMergeAssetSubType_Score,
            'enmMergeHouseSubType_Box' => self::enmMergeHouseSubType_Box,
            'enmMergeHouseSubType_Element' => self::enmMergeHouseSubType_Element,
            'enmMergeHouseSubType_Plan' => self::enmMergeHouseSubType_Plan,
            'enmMergeHouseSubType_BoxNotPutBack' => self::enmMergeHouseSubType_BoxNotPutBack,
            'enmItemExtraType_Mask' => self::enmItemExtraType_Mask,
            'enmItemPropsBillWedExtraType_Card' => self::enmItemPropsBillWedExtraType_Card,
            'enmItemPropsBillWedExtraType_Stage' => self::enmItemPropsBillWedExtraType_Stage,
            'enmItemPropsBillWedExtraType_Cloth' => self::enmItemPropsBillWedExtraType_Cloth,
            'enmItemPropsBillWedExtraType_Ring' => self::enmItemPropsBillWedExtraType_Ring,
            'enmTownProduceExtraType_Farm' => self::enmTownProduceExtraType_Farm,
            'enmTownProduceExtraType_Pasture' => self::enmTownProduceExtraType_Pasture,
            'enmTownProduceExtraType_Well' => self::enmTownProduceExtraType_Well,
            'enmTownProduceExtraType_Color' => self::enmTownProduceExtraType_Color,
            'enmTownProduceExtraType_Cloth' => self::enmTownProduceExtraType_Cloth,
            'enmTownProduceExtraType_Material' => self::enmTownProduceExtraType_Material,
            'enmTownProduceExtraType_Food' => self::enmTownProduceExtraType_Food,
            'enmItemPropsActBPExtraType_Exchange' => self::enmItemPropsActBPExtraType_Exchange,
            'enmItemPropsActBPExtraType_TaskCard' => self::enmItemPropsActBPExtraType_TaskCard,
            'enmItemPropsActMoneyExtraType_Puzzle' => self::enmItemPropsActMoneyExtraType_Puzzle,
            'enmItemGamePropsBPExtraType_Exp' => self::enmItemGamePropsBPExtraType_Exp,
            'enmItemGamePropsBPExtraType_ActiveLimit' => self::enmItemGamePropsBPExtraType_ActiveLimit,
            'enmItemGamePropsBPExtraType_Purchase' => self::enmItemGamePropsBPExtraType_Purchase,
            'enmItemGamePropsBPExtraType_Level' => self::enmItemGamePropsBPExtraType_Level,
            'enmItemGamePropsBPExtraType_Active' => self::enmItemGamePropsBPExtraType_Active,
            'enmItemGamePropsTourExtraType_TreeKey' => self::enmItemGamePropsTourExtraType_TreeKey,
            'enmItemGamePropsTourExtraType_Part' => self::enmItemGamePropsTourExtraType_Part,
            'enmItemPropsBoxExtraType_Wish' => self::enmItemPropsBoxExtraType_Wish,
            'enmItemPropsBoxExtraType_Hide' => self::enmItemPropsBoxExtraType_Hide,
            'enmItemGamePropsCoupleExtraType_Exp' => self::enmItemGamePropsCoupleExtraType_Exp,
            'enmItemGamePropsCoupleExtraType_Love' => self::enmItemGamePropsCoupleExtraType_Love,
            'enmItemGamePropsCoupleExtraType_Purchase' => self::enmItemGamePropsCoupleExtraType_Purchase,
            'enmItemGamePropsCoupleExtraType_PetHouse' => self::enmItemGamePropsCoupleExtraType_PetHouse,
        );
    }
}
}