<?php
/**
 * Auto generated from define_2.proto at 2023-02-13 12:39:22
 */

namespace Xnhd\Core\Pb\Sdo {
/**
 * KeyInfo enum
 */
final class KeyInfo
{
    const enmKeyInfo_None = 0;
    const enmKeyInfo_Left = 1;
    const enmKeyInfo_Right = 2;
    const enmKeyInfo_LeftRight = 3;
    const enmKeyInfo_Space = 4;
    const enmKeyInfo_Up = 5;
    const enmKeyInfo_Down = 6;
    const enmKeyInfo_LeftUp = 7;
    const enmKeyInfo_LeftDown = 8;
    const enmKeyInfo_RightUp = 9;
    const enmKeyInfo_RightDown = 10;
    const enmKeyInfo_Any = 11;
    const enmKeyInfo_I = 12;
    const enmKeyInfo_J = 13;
    const enmKeyInfo_K = 14;
    const enmKeyInfo_L = 15;
    const enmKeyInfo_LWSingle = 1;
    const enmKeyInfo_LWDouble = 2;
    const enmKeyInfo_LWSlide = 3;
    const enmKeyInfo_FeverTime = 4;
    const enmKeyInfo_ShowTime = 12;
    const enmKeyInfo_ValueMask = 15;
    const enmKeyInfo_Normal = 0;
    const enmKeyInfo_Normal_Way = 16;
    const enmKeyInfo_Normal_Long = 32;
    const enmKeyInfo_Double = 48;
    const enmKeyInfo_Double_Way = 64;
    const enmKeyInfo_Double_Long = 80;
    const enmKeyInfo_Heart = 96;
    const enmKeyInfo_DJKey1 = 1;
    const enmKeyInfo_DJKey2 = 2;
    const enmKeyInfo_DJKey3 = 3;
    const enmKeyInfo_DJKey4 = 4;
    const enmKeyInfo_DJKey5 = 5;
    const enmKeyInfo_DJKey6 = 6;
    const enmKeyInfo_DJKey7 = 7;
    const enmKeyInfo_DJNormal = 0;
    const enmKeyInfo_DJPress = 16;
    const enmKeyInfo_DJSlide = 32;
    const enmKeyInfo_Press = 16;
    const enmKeyInfo_Triggle = 32;
    const enmKeyInfo_Balloon4 = 48;
    const enmKeyInfo_Balloon6 = 64;
    const enmKeyInfo_Balloon8 = 80;
    const enmKeyInfo_Balloon10 = 96;
    const enmKeyInfo_Balloon12 = 112;
    const enmKeyInfo_Bonus = 128;
    const enmKeyInfo_ModeMask = 240;
    const enmKeyInfo_AUKeyMask = 255;
    const enmKeyInfo_SoundDefault = 0;
    const enmKeyInfo_SoundMask = 65280;
    const enmKeyValue_DJ_D = 1;
    const enmKeyValue_DJ_F = 2;
    const enmKeyValue_DJ_J = 3;
    const enmKeyValue_DJ_K = 4;
    const enmKeyValue_DJ_LD = 5;
    const enmKeyValue_DJ_LF = 6;
    const enmKeyValue_DJ_LJ = 7;
    const enmKeyValue_DJ_LK = 8;
    const enmKeyInfo_ComplexKey_Mask = 983040;
    const enmKeyInfo_Complex_Normal = 267452415;
    const enmKeyInfo_Complex_Invalid = 65536;
    const enmKeyInfo_Complex_Reverse = 131072;
    const enmKeyInfo_Complex_Block = 196608;
    const enmKeyInfo_SPerfect = 1048576;
    const enmKeyInfo_Perfect = 2097152;
    const enmKeyInfo_Great = 3145728;
    const enmKeyInfo_Good = 4194304;
    const enmKeyInfo_Miss = 5242880;
    const enmKeyInfo_Freedom = 6291456;
    const enmKeyInfo_Lost = 7340032;
    const enmKeyInfo_AccuracyMask = 15728640;
    const enmKeyInfo_HeartStar_Normal = 1;
    const enmKeyInfo_HeartStar_Slide = 2;
    const enmKeyInfo_HeartStar_Long = 3;
    const enmKeyInfo_HeartStar_Bend = 4;
    const enmKeyInfo_TT_Normal = 1;
    const enmKeyInfo_TT_Slide = 2;
    const enmKeyInfo_TT_Long = 3;
    const enmKeyInfo_TT_Click = 4;
    const enmKeyInfo_DROPBALL_Normal = 1;
    const enmKeyInfo_DROPBALL_LongStart = 2;
    const enmKeyInfo_DROPBALL_LongPress_Stay = 3;
    const enmKeyInfo_DROPBALL_LongPress_Move = 4;
    const enmKeyInfo_DROPBALL_Slide_Left = 5;
    const enmKeyInfo_DROPBALL_Slide_Right = 6;
    const enmKeyInfo_LMKey1 = 0;
    const enmKeyInfo_LMKey2 = 1;
    const enmKeyInfo_LMKey3 = 2;
    const enmKeyInfo_LMKey4 = 3;
    const enmKeyInfo_LMKey5 = 4;
    const enmKeyInfo_LMKey6 = 5;
    const enmKeyInfo_LMKey7 = 6;
    const enmKeyInfo_LMKey8 = 7;
    const enmKeyInfo_LMKey0 = 8;
    const enmKeyInfo_LMNone = 0;
    const enmKeyInfo_LMLeft1 = 32;
    const enmKeyInfo_LMLeft2 = 48;
    const enmKeyInfo_LMRight1 = 64;
    const enmKeyInfo_LMRight2 = 80;
    const enmKeyInfo_LMDirection_Mask = 240;
    const enmKeyInfo_LMKeyType_SingleKey = 1;
    const enmKeyInfo_LMKeyType_Slide = 2;
    const enmKeyInfo_LMKeyType_LongKey = 3;
    const enmKeyInfo_LMKeyType_Double = 4;
    const enmKeyInfo_LMKeyType_RoundKey = 5;
    const enmKeyInfo_LMKeyType_Node = 6;
    const enmKeyInfo_LMKeyType_Ball = 7;
    const enmKeyInfo_LMKeyType_DoubleNode = 8;
    const enmKeyInfo_LMKeyType_Mask = 3840;
    const enmKeyInfo_LMModeMask = 4080;
    const enmKeyInfo_LMKeyMask = 4095;
    const enmKeyInfo_RUNNINGBALL_Single = 1;
    const enmKeyInfo_RUNNINGBALL_Double = 2;
    const enmKeyInfo_RUNNINGBALL_Long = 3;
    const enmKeyInfo_RUNNINGBALL_Slide = 4;
    const enmKeyInfo_RUNNINGBALL_ComboHits = 5;
    const enmKeyInfo_RUNNINGBALL_Ignore = 7;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'enmKeyInfo_None' => self::enmKeyInfo_None,
            'enmKeyInfo_Left' => self::enmKeyInfo_Left,
            'enmKeyInfo_Right' => self::enmKeyInfo_Right,
            'enmKeyInfo_LeftRight' => self::enmKeyInfo_LeftRight,
            'enmKeyInfo_Space' => self::enmKeyInfo_Space,
            'enmKeyInfo_Up' => self::enmKeyInfo_Up,
            'enmKeyInfo_Down' => self::enmKeyInfo_Down,
            'enmKeyInfo_LeftUp' => self::enmKeyInfo_LeftUp,
            'enmKeyInfo_LeftDown' => self::enmKeyInfo_LeftDown,
            'enmKeyInfo_RightUp' => self::enmKeyInfo_RightUp,
            'enmKeyInfo_RightDown' => self::enmKeyInfo_RightDown,
            'enmKeyInfo_Any' => self::enmKeyInfo_Any,
            'enmKeyInfo_I' => self::enmKeyInfo_I,
            'enmKeyInfo_J' => self::enmKeyInfo_J,
            'enmKeyInfo_K' => self::enmKeyInfo_K,
            'enmKeyInfo_L' => self::enmKeyInfo_L,
            'enmKeyInfo_LWSingle' => self::enmKeyInfo_LWSingle,
            'enmKeyInfo_LWDouble' => self::enmKeyInfo_LWDouble,
            'enmKeyInfo_LWSlide' => self::enmKeyInfo_LWSlide,
            'enmKeyInfo_FeverTime' => self::enmKeyInfo_FeverTime,
            'enmKeyInfo_ShowTime' => self::enmKeyInfo_ShowTime,
            'enmKeyInfo_ValueMask' => self::enmKeyInfo_ValueMask,
            'enmKeyInfo_Normal' => self::enmKeyInfo_Normal,
            'enmKeyInfo_Normal_Way' => self::enmKeyInfo_Normal_Way,
            'enmKeyInfo_Normal_Long' => self::enmKeyInfo_Normal_Long,
            'enmKeyInfo_Double' => self::enmKeyInfo_Double,
            'enmKeyInfo_Double_Way' => self::enmKeyInfo_Double_Way,
            'enmKeyInfo_Double_Long' => self::enmKeyInfo_Double_Long,
            'enmKeyInfo_Heart' => self::enmKeyInfo_Heart,
            'enmKeyInfo_DJKey1' => self::enmKeyInfo_DJKey1,
            'enmKeyInfo_DJKey2' => self::enmKeyInfo_DJKey2,
            'enmKeyInfo_DJKey3' => self::enmKeyInfo_DJKey3,
            'enmKeyInfo_DJKey4' => self::enmKeyInfo_DJKey4,
            'enmKeyInfo_DJKey5' => self::enmKeyInfo_DJKey5,
            'enmKeyInfo_DJKey6' => self::enmKeyInfo_DJKey6,
            'enmKeyInfo_DJKey7' => self::enmKeyInfo_DJKey7,
            'enmKeyInfo_DJNormal' => self::enmKeyInfo_DJNormal,
            'enmKeyInfo_DJPress' => self::enmKeyInfo_DJPress,
            'enmKeyInfo_DJSlide' => self::enmKeyInfo_DJSlide,
            'enmKeyInfo_Press' => self::enmKeyInfo_Press,
            'enmKeyInfo_Triggle' => self::enmKeyInfo_Triggle,
            'enmKeyInfo_Balloon4' => self::enmKeyInfo_Balloon4,
            'enmKeyInfo_Balloon6' => self::enmKeyInfo_Balloon6,
            'enmKeyInfo_Balloon8' => self::enmKeyInfo_Balloon8,
            'enmKeyInfo_Balloon10' => self::enmKeyInfo_Balloon10,
            'enmKeyInfo_Balloon12' => self::enmKeyInfo_Balloon12,
            'enmKeyInfo_Bonus' => self::enmKeyInfo_Bonus,
            'enmKeyInfo_ModeMask' => self::enmKeyInfo_ModeMask,
            'enmKeyInfo_AUKeyMask' => self::enmKeyInfo_AUKeyMask,
            'enmKeyInfo_SoundDefault' => self::enmKeyInfo_SoundDefault,
            'enmKeyInfo_SoundMask' => self::enmKeyInfo_SoundMask,
            'enmKeyValue_DJ_D' => self::enmKeyValue_DJ_D,
            'enmKeyValue_DJ_F' => self::enmKeyValue_DJ_F,
            'enmKeyValue_DJ_J' => self::enmKeyValue_DJ_J,
            'enmKeyValue_DJ_K' => self::enmKeyValue_DJ_K,
            'enmKeyValue_DJ_LD' => self::enmKeyValue_DJ_LD,
            'enmKeyValue_DJ_LF' => self::enmKeyValue_DJ_LF,
            'enmKeyValue_DJ_LJ' => self::enmKeyValue_DJ_LJ,
            'enmKeyValue_DJ_LK' => self::enmKeyValue_DJ_LK,
            'enmKeyInfo_ComplexKey_Mask' => self::enmKeyInfo_ComplexKey_Mask,
            'enmKeyInfo_Complex_Normal' => self::enmKeyInfo_Complex_Normal,
            'enmKeyInfo_Complex_Invalid' => self::enmKeyInfo_Complex_Invalid,
            'enmKeyInfo_Complex_Reverse' => self::enmKeyInfo_Complex_Reverse,
            'enmKeyInfo_Complex_Block' => self::enmKeyInfo_Complex_Block,
            'enmKeyInfo_SPerfect' => self::enmKeyInfo_SPerfect,
            'enmKeyInfo_Perfect' => self::enmKeyInfo_Perfect,
            'enmKeyInfo_Great' => self::enmKeyInfo_Great,
            'enmKeyInfo_Good' => self::enmKeyInfo_Good,
            'enmKeyInfo_Miss' => self::enmKeyInfo_Miss,
            'enmKeyInfo_Freedom' => self::enmKeyInfo_Freedom,
            'enmKeyInfo_Lost' => self::enmKeyInfo_Lost,
            'enmKeyInfo_AccuracyMask' => self::enmKeyInfo_AccuracyMask,
            'enmKeyInfo_HeartStar_Normal' => self::enmKeyInfo_HeartStar_Normal,
            'enmKeyInfo_HeartStar_Slide' => self::enmKeyInfo_HeartStar_Slide,
            'enmKeyInfo_HeartStar_Long' => self::enmKeyInfo_HeartStar_Long,
            'enmKeyInfo_HeartStar_Bend' => self::enmKeyInfo_HeartStar_Bend,
            'enmKeyInfo_TT_Normal' => self::enmKeyInfo_TT_Normal,
            'enmKeyInfo_TT_Slide' => self::enmKeyInfo_TT_Slide,
            'enmKeyInfo_TT_Long' => self::enmKeyInfo_TT_Long,
            'enmKeyInfo_TT_Click' => self::enmKeyInfo_TT_Click,
            'enmKeyInfo_DROPBALL_Normal' => self::enmKeyInfo_DROPBALL_Normal,
            'enmKeyInfo_DROPBALL_LongStart' => self::enmKeyInfo_DROPBALL_LongStart,
            'enmKeyInfo_DROPBALL_LongPress_Stay' => self::enmKeyInfo_DROPBALL_LongPress_Stay,
            'enmKeyInfo_DROPBALL_LongPress_Move' => self::enmKeyInfo_DROPBALL_LongPress_Move,
            'enmKeyInfo_DROPBALL_Slide_Left' => self::enmKeyInfo_DROPBALL_Slide_Left,
            'enmKeyInfo_DROPBALL_Slide_Right' => self::enmKeyInfo_DROPBALL_Slide_Right,
            'enmKeyInfo_LMKey1' => self::enmKeyInfo_LMKey1,
            'enmKeyInfo_LMKey2' => self::enmKeyInfo_LMKey2,
            'enmKeyInfo_LMKey3' => self::enmKeyInfo_LMKey3,
            'enmKeyInfo_LMKey4' => self::enmKeyInfo_LMKey4,
            'enmKeyInfo_LMKey5' => self::enmKeyInfo_LMKey5,
            'enmKeyInfo_LMKey6' => self::enmKeyInfo_LMKey6,
            'enmKeyInfo_LMKey7' => self::enmKeyInfo_LMKey7,
            'enmKeyInfo_LMKey8' => self::enmKeyInfo_LMKey8,
            'enmKeyInfo_LMKey0' => self::enmKeyInfo_LMKey0,
            'enmKeyInfo_LMNone' => self::enmKeyInfo_LMNone,
            'enmKeyInfo_LMLeft1' => self::enmKeyInfo_LMLeft1,
            'enmKeyInfo_LMLeft2' => self::enmKeyInfo_LMLeft2,
            'enmKeyInfo_LMRight1' => self::enmKeyInfo_LMRight1,
            'enmKeyInfo_LMRight2' => self::enmKeyInfo_LMRight2,
            'enmKeyInfo_LMDirection_Mask' => self::enmKeyInfo_LMDirection_Mask,
            'enmKeyInfo_LMKeyType_SingleKey' => self::enmKeyInfo_LMKeyType_SingleKey,
            'enmKeyInfo_LMKeyType_Slide' => self::enmKeyInfo_LMKeyType_Slide,
            'enmKeyInfo_LMKeyType_LongKey' => self::enmKeyInfo_LMKeyType_LongKey,
            'enmKeyInfo_LMKeyType_Double' => self::enmKeyInfo_LMKeyType_Double,
            'enmKeyInfo_LMKeyType_RoundKey' => self::enmKeyInfo_LMKeyType_RoundKey,
            'enmKeyInfo_LMKeyType_Node' => self::enmKeyInfo_LMKeyType_Node,
            'enmKeyInfo_LMKeyType_Ball' => self::enmKeyInfo_LMKeyType_Ball,
            'enmKeyInfo_LMKeyType_DoubleNode' => self::enmKeyInfo_LMKeyType_DoubleNode,
            'enmKeyInfo_LMKeyType_Mask' => self::enmKeyInfo_LMKeyType_Mask,
            'enmKeyInfo_LMModeMask' => self::enmKeyInfo_LMModeMask,
            'enmKeyInfo_LMKeyMask' => self::enmKeyInfo_LMKeyMask,
            'enmKeyInfo_RUNNINGBALL_Single' => self::enmKeyInfo_RUNNINGBALL_Single,
            'enmKeyInfo_RUNNINGBALL_Double' => self::enmKeyInfo_RUNNINGBALL_Double,
            'enmKeyInfo_RUNNINGBALL_Long' => self::enmKeyInfo_RUNNINGBALL_Long,
            'enmKeyInfo_RUNNINGBALL_Slide' => self::enmKeyInfo_RUNNINGBALL_Slide,
            'enmKeyInfo_RUNNINGBALL_ComboHits' => self::enmKeyInfo_RUNNINGBALL_ComboHits,
            'enmKeyInfo_RUNNINGBALL_Ignore' => self::enmKeyInfo_RUNNINGBALL_Ignore,
        );
    }
}
}