<?php
/**
 * Auto generated from accountdbserver.proto at 2023-02-13 12:39:16
 */

namespace Xnhd\Core\Pb\Sdo {
/**
 * MSGID_ACCOUNTDBSERVER enum
 */
final class MSGID_ACCOUNTDBSERVER
{
    const MSGID_CADB_REQ_GETACCOUNTINFO = 257;
    const MSGID_ADBC_RESP_GETACCOUNTINFO = 33025;
    const MSGID_CADB_REQ_CREATEROLE = 258;
    const MSGID_ADBC_RESP_CREATEROLE = 33026;
    const MSGID_ADBC_NOTI_CREATEROLE = 16642;
    const MSGID_CADB_REQ_GETROLEINFO = 259;
    const MSGID_ADBC_RESP_GETROLEINFO = 33027;
    const MSGID_CADB_REQ_CHECKROLENAME = 260;
    const MSGID_ADBC_RESP_CHECKROLENAME = 33028;
    const MSGID_CADB_REQ_GMDELETEROLE = 417;
    const MSGID_ADBC_RESP_GMDELETEROLE = 33185;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'MSGID_CADB_REQ_GETACCOUNTINFO' => self::MSGID_CADB_REQ_GETACCOUNTINFO,
            'MSGID_ADBC_RESP_GETACCOUNTINFO' => self::MSGID_ADBC_RESP_GETACCOUNTINFO,
            'MSGID_CADB_REQ_CREATEROLE' => self::MSGID_CADB_REQ_CREATEROLE,
            'MSGID_ADBC_RESP_CREATEROLE' => self::MSGID_ADBC_RESP_CREATEROLE,
            'MSGID_ADBC_NOTI_CREATEROLE' => self::MSGID_ADBC_NOTI_CREATEROLE,
            'MSGID_CADB_REQ_GETROLEINFO' => self::MSGID_CADB_REQ_GETROLEINFO,
            'MSGID_ADBC_RESP_GETROLEINFO' => self::MSGID_ADBC_RESP_GETROLEINFO,
            'MSGID_CADB_REQ_CHECKROLENAME' => self::MSGID_CADB_REQ_CHECKROLENAME,
            'MSGID_ADBC_RESP_CHECKROLENAME' => self::MSGID_ADBC_RESP_CHECKROLENAME,
            'MSGID_CADB_REQ_GMDELETEROLE' => self::MSGID_CADB_REQ_GMDELETEROLE,
            'MSGID_ADBC_RESP_GMDELETEROLE' => self::MSGID_ADBC_RESP_GMDELETEROLE,
        );
    }
}
}