<?php
/**
 * Auto generated from stateserver.proto at 2023-02-13 12:39:20
 */

namespace Xnhd\Core\Pb\Sdo {
/**
 * MSGID_STATESERVER enum
 */
final class MSGID_STATESERVER
{
    const MSGID_CSTS_REQ_LOGIN = 513;
    const MSGID_STSC_RESP_LOGIN = 33281;
    const MSGID_STSC_NOTI_LOGIN = 16897;
    const MSGID_CSTS_REQ_QUEUEINFO = 514;
    const MSGID_STSC_RESP_QUEUEINFO = 33282;
    const MSGID_STSC_NOTI_QUEUEINFO = 16898;
    const MSGID_CSTS_REQ_LEAVEQUEUE = 515;
    const MSGID_STSC_RESP_LEAVEQUEUE = 33283;
    const MSGID_CSTS_REQ_ENTERGAME = 516;
    const MSGID_STSC_RESP_ENTERGAME = 33284;
    const MSGID_STSC_NOTI_FORCELOGOUT = 16901;
    const MSGID_CSTS_REQ_HEARTBEAT = 518;
    const MSGID_STSC_RESP_HEARTBEAT = 33286;
    const MSGID_CSTS_REQ_RECONNECT = 519;
    const MSGID_STSC_RESP_RECONNECT = 33287;
    const MSGID_CSTS_REQ_KICKALLPLAYER = 520;
    const MSGID_STSC_RESP_KICKALLPLAYER = 33288;
    const MSGID_STSC_NOTI_KICKPLAYER = 16905;
    const MSGID_STSC_NOTI_RELOGIN = 16906;
    const MSGID_CSTS_REQ_REGISTER = 523;
    const MSGID_STSC_RESP_REGISTER = 33291;
    const MSGID_CSTS_REQ_BAN = 528;
    const MSGID_STSC_RESP_BAN = 33296;
    const MSGID_CSTS_REQ_CANCELBAN = 529;
    const MSGID_STSC_RESP_CANCELBAN = 33297;
    const MSGID_CSTS_REQ_GETBANLIST = 530;
    const MSGID_STSC_RESP_GETBANLIST = 33298;
    const MSGID_CSTS_REQ_GETROLESTATE = 544;
    const MSGID_STSC_RESP_GETROLESTATE = 33312;
    const MSGID_STSC_NOTI_ROLESTATEUPDATE = 16928;
    const MSGID_CSTS_REQ_GETCHANNELSTATUS = 545;
    const MSGID_STSC_RESP_GETCHANNELSTATUS = 33313;
    const MSGID_CSTS_REQ_ENTERCHANNEL = 546;
    const MSGID_STSC_RESP_ENTERCHANNEL = 33314;
    const MSGID_CSTS_REQ_GETIDLEPLAYERS = 547;
    const MSGID_STSC_RESP_GETIDLEPLAYERS = 33315;
    const MSGID_CSTS_REQ_GETREALMINFO = 548;
    const MSGID_STSC_RESP_GETREALMINFO = 33316;
    const MSGID_CSTS_REQ_SETSERVERSTATE = 672;
    const MSGID_STSC_RESP_SETSERVERSTATE = 33440;
    const MSGID_CSTS_REQ_GETSERVERSTATE = 673;
    const MSGID_STSC_RESP_GETSERVERSTATE = 33441;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'MSGID_CSTS_REQ_LOGIN' => self::MSGID_CSTS_REQ_LOGIN,
            'MSGID_STSC_RESP_LOGIN' => self::MSGID_STSC_RESP_LOGIN,
            'MSGID_STSC_NOTI_LOGIN' => self::MSGID_STSC_NOTI_LOGIN,
            'MSGID_CSTS_REQ_QUEUEINFO' => self::MSGID_CSTS_REQ_QUEUEINFO,
            'MSGID_STSC_RESP_QUEUEINFO' => self::MSGID_STSC_RESP_QUEUEINFO,
            'MSGID_STSC_NOTI_QUEUEINFO' => self::MSGID_STSC_NOTI_QUEUEINFO,
            'MSGID_CSTS_REQ_LEAVEQUEUE' => self::MSGID_CSTS_REQ_LEAVEQUEUE,
            'MSGID_STSC_RESP_LEAVEQUEUE' => self::MSGID_STSC_RESP_LEAVEQUEUE,
            'MSGID_CSTS_REQ_ENTERGAME' => self::MSGID_CSTS_REQ_ENTERGAME,
            'MSGID_STSC_RESP_ENTERGAME' => self::MSGID_STSC_RESP_ENTERGAME,
            'MSGID_STSC_NOTI_FORCELOGOUT' => self::MSGID_STSC_NOTI_FORCELOGOUT,
            'MSGID_CSTS_REQ_HEARTBEAT' => self::MSGID_CSTS_REQ_HEARTBEAT,
            'MSGID_STSC_RESP_HEARTBEAT' => self::MSGID_STSC_RESP_HEARTBEAT,
            'MSGID_CSTS_REQ_RECONNECT' => self::MSGID_CSTS_REQ_RECONNECT,
            'MSGID_STSC_RESP_RECONNECT' => self::MSGID_STSC_RESP_RECONNECT,
            'MSGID_CSTS_REQ_KICKALLPLAYER' => self::MSGID_CSTS_REQ_KICKALLPLAYER,
            'MSGID_STSC_RESP_KICKALLPLAYER' => self::MSGID_STSC_RESP_KICKALLPLAYER,
            'MSGID_STSC_NOTI_KICKPLAYER' => self::MSGID_STSC_NOTI_KICKPLAYER,
            'MSGID_STSC_NOTI_RELOGIN' => self::MSGID_STSC_NOTI_RELOGIN,
            'MSGID_CSTS_REQ_REGISTER' => self::MSGID_CSTS_REQ_REGISTER,
            'MSGID_STSC_RESP_REGISTER' => self::MSGID_STSC_RESP_REGISTER,
            'MSGID_CSTS_REQ_BAN' => self::MSGID_CSTS_REQ_BAN,
            'MSGID_STSC_RESP_BAN' => self::MSGID_STSC_RESP_BAN,
            'MSGID_CSTS_REQ_CANCELBAN' => self::MSGID_CSTS_REQ_CANCELBAN,
            'MSGID_STSC_RESP_CANCELBAN' => self::MSGID_STSC_RESP_CANCELBAN,
            'MSGID_CSTS_REQ_GETBANLIST' => self::MSGID_CSTS_REQ_GETBANLIST,
            'MSGID_STSC_RESP_GETBANLIST' => self::MSGID_STSC_RESP_GETBANLIST,
            'MSGID_CSTS_REQ_GETROLESTATE' => self::MSGID_CSTS_REQ_GETROLESTATE,
            'MSGID_STSC_RESP_GETROLESTATE' => self::MSGID_STSC_RESP_GETROLESTATE,
            'MSGID_STSC_NOTI_ROLESTATEUPDATE' => self::MSGID_STSC_NOTI_ROLESTATEUPDATE,
            'MSGID_CSTS_REQ_GETCHANNELSTATUS' => self::MSGID_CSTS_REQ_GETCHANNELSTATUS,
            'MSGID_STSC_RESP_GETCHANNELSTATUS' => self::MSGID_STSC_RESP_GETCHANNELSTATUS,
            'MSGID_CSTS_REQ_ENTERCHANNEL' => self::MSGID_CSTS_REQ_ENTERCHANNEL,
            'MSGID_STSC_RESP_ENTERCHANNEL' => self::MSGID_STSC_RESP_ENTERCHANNEL,
            'MSGID_CSTS_REQ_GETIDLEPLAYERS' => self::MSGID_CSTS_REQ_GETIDLEPLAYERS,
            'MSGID_STSC_RESP_GETIDLEPLAYERS' => self::MSGID_STSC_RESP_GETIDLEPLAYERS,
            'MSGID_CSTS_REQ_GETREALMINFO' => self::MSGID_CSTS_REQ_GETREALMINFO,
            'MSGID_STSC_RESP_GETREALMINFO' => self::MSGID_STSC_RESP_GETREALMINFO,
            'MSGID_CSTS_REQ_SETSERVERSTATE' => self::MSGID_CSTS_REQ_SETSERVERSTATE,
            'MSGID_STSC_RESP_SETSERVERSTATE' => self::MSGID_STSC_RESP_SETSERVERSTATE,
            'MSGID_CSTS_REQ_GETSERVERSTATE' => self::MSGID_CSTS_REQ_GETSERVERSTATE,
            'MSGID_STSC_RESP_GETSERVERSTATE' => self::MSGID_STSC_RESP_GETSERVERSTATE,
        );
    }
}
}