<?php
/**
 * Auto generated from taskserver.proto at 2023-02-13 12:39:17
 */

namespace Xnhd\Core\Pb\Sdo {
/**
 * MSGID_TASKSERVER enum
 */
final class MSGID_TASKSERVER
{
    const MSGID_CTAS_REQ_TASKINFO = 3329;
    const MSGID_TASC_RESP_TASKINFO = 36097;
    const MSGID_TASC_NOTI_TASKINFO = 19713;
    const MSGID_CTAS_REQ_TASKPRIZE = 3330;
    const MSGID_TASC_RESP_TASKPRIZE = 36098;
    const MSGID_CTAS_REQ_TASKACCELERATE = 3331;
    const MSGID_TASC_RESP_TASKACCELERATE = 36099;
    const MSGID_CTAS_REQ_TASKREFRESH = 3332;
    const MSGID_TASC_RESP_TASKREFRESH = 36100;
    const MSGID_CTAS_REQ_TASKGUILD = 3333;
    const MSGID_TASC_RESP_TASKGUILD = 36101;
    const MSGID_CTAS_REQ_ACHIEVEMENTINFO = 3344;
    const MSGID_TASC_RESP_ACHIEVEMENTINFO = 36112;
    const MSGID_TASC_NOTI_ACHIEVEMENTINFO = 19728;
    const MSGID_CTAS_REQ_ACHIEVEMENTPRIZE = 3345;
    const MSGID_TASC_RESP_ACHIEVEMENTPRIZE = 36113;
    const MSGID_CTAS_REQ_GETMYWORKINFO = 3360;
    const MSGID_TASC_RESP_GETMYWORKINFO = 36128;
    const MSGID_TASC_NOTI_MYWORKINFO = 19744;
    const MSGID_CTAS_REQ_GETWORKINFOLIST = 3361;
    const MSGID_TASC_RESP_GETWORKINFOLIST = 36129;
    const MSGID_CTAS_REQ_SETWORKRECORD = 3362;
    const MSGID_TASC_RESP_SETWORKRECORD = 36130;
    const MSGID_TASC_NOTI_SETWORKRECORD = 19746;
    const MSGID_CTAS_REQ_GETWORKPRIZE = 3363;
    const MSGID_TASC_RESP_GETWORKPRIZE = 36131;
    const MSGID_CTAS_REQ_RECEIVEWORKPRIZE = 3364;
    const MSGID_TASC_RESP_RECEIVEWORKPRIZE = 36132;
    const MSGID_TASC_NOTI_WORKPRIZE = 19749;
    const MSGID_CTAS_REQ_WORKDANCE = 3366;
    const MSGID_TASC_RESP_WORKDANCE = 36134;
    const MSGID_CTAS_REQ_QUICKDONEWORK = 3367;
    const MSGID_TASC_RESP_QUICKDONEWORK = 36135;
    const MSGID_CTAS_REQ_ADDTIMES = 3368;
    const MSGID_TASC_RESP_ADDTIMES = 36136;
    const MSGID_CTAS_REQ_GETTOURINFO = 3369;
    const MSGID_TASC_RESP_GETTOURINFO = 36137;
    const MSGID_CTAS_REQ_RECEIVETOURREWARD = 3370;
    const MSGID_TASC_RESP_RECEIVETOURREWARD = 36138;
    const MSGID_CTAS_REQ_SETPUZZLECUSTOMIZE = 3372;
    const MSGID_TASC_RESP_SETPUZZLECUSTOMIZE = 36140;
    const MSGID_CTAS_REQ_PROCPUZZLEEXCHANGE = 3374;
    const MSGID_TASC_RESP_PROCPUZZLEEXCHANGE = 36142;
    const MSGID_CTAS_REQ_GETPUZZLECOLLECTLIST = 3375;
    const MSGID_TASC_RESP_GETPUZZLECOLLECTLIST = 36143;
    const MSGID_CTAS_REQ_GETTOURPUZZLE = 3376;
    const MSGID_TASC_RESP_GETTOURPUZZLE = 36144;
    const MSGID_TASC_NOTI_ADDPUZZLEPART = 19761;
    const MSGID_CTAS_REQ_GETREWARDINFO = 3377;
    const MSGID_TASC_RESP_GETREWARDINFO = 36145;
    const MSGID_CTAS_REQ_ADDPUZZLEPART = 3378;
    const MSGID_TASC_RESP_ADDPUZZLEPART = 36146;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'MSGID_CTAS_REQ_TASKINFO' => self::MSGID_CTAS_REQ_TASKINFO,
            'MSGID_TASC_RESP_TASKINFO' => self::MSGID_TASC_RESP_TASKINFO,
            'MSGID_TASC_NOTI_TASKINFO' => self::MSGID_TASC_NOTI_TASKINFO,
            'MSGID_CTAS_REQ_TASKPRIZE' => self::MSGID_CTAS_REQ_TASKPRIZE,
            'MSGID_TASC_RESP_TASKPRIZE' => self::MSGID_TASC_RESP_TASKPRIZE,
            'MSGID_CTAS_REQ_TASKACCELERATE' => self::MSGID_CTAS_REQ_TASKACCELERATE,
            'MSGID_TASC_RESP_TASKACCELERATE' => self::MSGID_TASC_RESP_TASKACCELERATE,
            'MSGID_CTAS_REQ_TASKREFRESH' => self::MSGID_CTAS_REQ_TASKREFRESH,
            'MSGID_TASC_RESP_TASKREFRESH' => self::MSGID_TASC_RESP_TASKREFRESH,
            'MSGID_CTAS_REQ_TASKGUILD' => self::MSGID_CTAS_REQ_TASKGUILD,
            'MSGID_TASC_RESP_TASKGUILD' => self::MSGID_TASC_RESP_TASKGUILD,
            'MSGID_CTAS_REQ_ACHIEVEMENTINFO' => self::MSGID_CTAS_REQ_ACHIEVEMENTINFO,
            'MSGID_TASC_RESP_ACHIEVEMENTINFO' => self::MSGID_TASC_RESP_ACHIEVEMENTINFO,
            'MSGID_TASC_NOTI_ACHIEVEMENTINFO' => self::MSGID_TASC_NOTI_ACHIEVEMENTINFO,
            'MSGID_CTAS_REQ_ACHIEVEMENTPRIZE' => self::MSGID_CTAS_REQ_ACHIEVEMENTPRIZE,
            'MSGID_TASC_RESP_ACHIEVEMENTPRIZE' => self::MSGID_TASC_RESP_ACHIEVEMENTPRIZE,
            'MSGID_CTAS_REQ_GETMYWORKINFO' => self::MSGID_CTAS_REQ_GETMYWORKINFO,
            'MSGID_TASC_RESP_GETMYWORKINFO' => self::MSGID_TASC_RESP_GETMYWORKINFO,
            'MSGID_TASC_NOTI_MYWORKINFO' => self::MSGID_TASC_NOTI_MYWORKINFO,
            'MSGID_CTAS_REQ_GETWORKINFOLIST' => self::MSGID_CTAS_REQ_GETWORKINFOLIST,
            'MSGID_TASC_RESP_GETWORKINFOLIST' => self::MSGID_TASC_RESP_GETWORKINFOLIST,
            'MSGID_CTAS_REQ_SETWORKRECORD' => self::MSGID_CTAS_REQ_SETWORKRECORD,
            'MSGID_TASC_RESP_SETWORKRECORD' => self::MSGID_TASC_RESP_SETWORKRECORD,
            'MSGID_TASC_NOTI_SETWORKRECORD' => self::MSGID_TASC_NOTI_SETWORKRECORD,
            'MSGID_CTAS_REQ_GETWORKPRIZE' => self::MSGID_CTAS_REQ_GETWORKPRIZE,
            'MSGID_TASC_RESP_GETWORKPRIZE' => self::MSGID_TASC_RESP_GETWORKPRIZE,
            'MSGID_CTAS_REQ_RECEIVEWORKPRIZE' => self::MSGID_CTAS_REQ_RECEIVEWORKPRIZE,
            'MSGID_TASC_RESP_RECEIVEWORKPRIZE' => self::MSGID_TASC_RESP_RECEIVEWORKPRIZE,
            'MSGID_TASC_NOTI_WORKPRIZE' => self::MSGID_TASC_NOTI_WORKPRIZE,
            'MSGID_CTAS_REQ_WORKDANCE' => self::MSGID_CTAS_REQ_WORKDANCE,
            'MSGID_TASC_RESP_WORKDANCE' => self::MSGID_TASC_RESP_WORKDANCE,
            'MSGID_CTAS_REQ_QUICKDONEWORK' => self::MSGID_CTAS_REQ_QUICKDONEWORK,
            'MSGID_TASC_RESP_QUICKDONEWORK' => self::MSGID_TASC_RESP_QUICKDONEWORK,
            'MSGID_CTAS_REQ_ADDTIMES' => self::MSGID_CTAS_REQ_ADDTIMES,
            'MSGID_TASC_RESP_ADDTIMES' => self::MSGID_TASC_RESP_ADDTIMES,
            'MSGID_CTAS_REQ_GETTOURINFO' => self::MSGID_CTAS_REQ_GETTOURINFO,
            'MSGID_TASC_RESP_GETTOURINFO' => self::MSGID_TASC_RESP_GETTOURINFO,
            'MSGID_CTAS_REQ_RECEIVETOURREWARD' => self::MSGID_CTAS_REQ_RECEIVETOURREWARD,
            'MSGID_TASC_RESP_RECEIVETOURREWARD' => self::MSGID_TASC_RESP_RECEIVETOURREWARD,
            'MSGID_CTAS_REQ_SETPUZZLECUSTOMIZE' => self::MSGID_CTAS_REQ_SETPUZZLECUSTOMIZE,
            'MSGID_TASC_RESP_SETPUZZLECUSTOMIZE' => self::MSGID_TASC_RESP_SETPUZZLECUSTOMIZE,
            'MSGID_CTAS_REQ_PROCPUZZLEEXCHANGE' => self::MSGID_CTAS_REQ_PROCPUZZLEEXCHANGE,
            'MSGID_TASC_RESP_PROCPUZZLEEXCHANGE' => self::MSGID_TASC_RESP_PROCPUZZLEEXCHANGE,
            'MSGID_CTAS_REQ_GETPUZZLECOLLECTLIST' => self::MSGID_CTAS_REQ_GETPUZZLECOLLECTLIST,
            'MSGID_TASC_RESP_GETPUZZLECOLLECTLIST' => self::MSGID_TASC_RESP_GETPUZZLECOLLECTLIST,
            'MSGID_CTAS_REQ_GETTOURPUZZLE' => self::MSGID_CTAS_REQ_GETTOURPUZZLE,
            'MSGID_TASC_RESP_GETTOURPUZZLE' => self::MSGID_TASC_RESP_GETTOURPUZZLE,
            'MSGID_TASC_NOTI_ADDPUZZLEPART' => self::MSGID_TASC_NOTI_ADDPUZZLEPART,
            'MSGID_CTAS_REQ_GETREWARDINFO' => self::MSGID_CTAS_REQ_GETREWARDINFO,
            'MSGID_TASC_RESP_GETREWARDINFO' => self::MSGID_TASC_RESP_GETREWARDINFO,
            'MSGID_CTAS_REQ_ADDPUZZLEPART' => self::MSGID_CTAS_REQ_ADDPUZZLEPART,
            'MSGID_TASC_RESP_ADDPUZZLEPART' => self::MSGID_TASC_RESP_ADDPUZZLEPART,
        );
    }
}
}