<?php
/**
 * Auto generated from mateserver.proto at 2023-02-13 12:39:22
 */

namespace Xnhd\Core\Pb\Sdo {
/**
 * MSGID_MATESERVER enum
 */
final class MSGID_MATESERVER
{
    const MSGID_CMAS_REQ_CREATEROOM = 1281;
    const MSGID_MASC_RESP_CREATEROOM = 34049;
    const MSGID_MASC_NOTI_CREATEROOM = 17665;
    const MSGID_CMAS_REQ_GETROOMLIST = 1282;
    const MSGID_MASC_RESP_GETROOMLIST = 34050;
    const MSGID_CMAS_REQ_GETROOMLISTINFO = 1283;
    const MSGID_MASC_RESP_GETROOMLISTINFO = 34051;
    const MSGID_CMAS_REQ_JOINROOM = 1284;
    const MSGID_MASC_RESP_JOINROOM = 34052;
    const MSGID_MASC_NOTI_JOINROOM = 17668;
    const MSGID_MASC_NOTI_DELETEROOM = 17669;
    const MSGID_CMAS_REQ_EXITROOM = 1286;
    const MSGID_MASC_RESP_EXITROOM = 34054;
    const MSGID_MASC_NOTI_EXITROOM = 17670;
    const MSGID_MASC_NOTI_KICKPLAYER = 17671;
    const MSGID_CMAS_REQ_INVITEPLAYER = 1288;
    const MSGID_MASC_RESP_INVITEPLAYER = 34056;
    const MSGID_MASC_NOTI_INVITEPLAYER = 17672;
    const MSGID_CMAS_REQ_ANSWERINVITE = 1289;
    const MSGID_MASC_RESP_ANSWERINVITE = 34057;
    const MSGID_MASC_NOTI_ANSWERINVITE = 17673;
    const MSGID_CMAS_REQ_TRACK = 1290;
    const MSGID_MASC_RESP_TRACK = 34058;
    const MSGID_CMAS_REQ_ENTERHOUSE = 1291;
    const MSGID_MASC_RESP_ENTERHOUSE = 34059;
    const MSGID_CMAS_REQ_ENTERSNSROOM = 1292;
    const MSGID_MASC_RESP_ENTERSNSROOM = 34060;
    const MSGID_CMAS_REQ_FIXUPMATCH = 1293;
    const MSGID_MASC_RESP_FIXUPMATCH = 34061;
    const MSGID_MASC_NOTI_FIXUPRESULT = 17677;
    const MSGID_CMAS_REQ_GETROOMINFOBYROOMID = 1294;
    const MSGID_MASC_RESP_GETROOMINFOBYROOMID = 34062;
    const MSGID_CMAS_REQ_GETMYWEDDINGROOM = 1295;
    const MSGID_MASC_RESP_GETMYWEDDINGROOM = 34063;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'MSGID_CMAS_REQ_CREATEROOM' => self::MSGID_CMAS_REQ_CREATEROOM,
            'MSGID_MASC_RESP_CREATEROOM' => self::MSGID_MASC_RESP_CREATEROOM,
            'MSGID_MASC_NOTI_CREATEROOM' => self::MSGID_MASC_NOTI_CREATEROOM,
            'MSGID_CMAS_REQ_GETROOMLIST' => self::MSGID_CMAS_REQ_GETROOMLIST,
            'MSGID_MASC_RESP_GETROOMLIST' => self::MSGID_MASC_RESP_GETROOMLIST,
            'MSGID_CMAS_REQ_GETROOMLISTINFO' => self::MSGID_CMAS_REQ_GETROOMLISTINFO,
            'MSGID_MASC_RESP_GETROOMLISTINFO' => self::MSGID_MASC_RESP_GETROOMLISTINFO,
            'MSGID_CMAS_REQ_JOINROOM' => self::MSGID_CMAS_REQ_JOINROOM,
            'MSGID_MASC_RESP_JOINROOM' => self::MSGID_MASC_RESP_JOINROOM,
            'MSGID_MASC_NOTI_JOINROOM' => self::MSGID_MASC_NOTI_JOINROOM,
            'MSGID_MASC_NOTI_DELETEROOM' => self::MSGID_MASC_NOTI_DELETEROOM,
            'MSGID_CMAS_REQ_EXITROOM' => self::MSGID_CMAS_REQ_EXITROOM,
            'MSGID_MASC_RESP_EXITROOM' => self::MSGID_MASC_RESP_EXITROOM,
            'MSGID_MASC_NOTI_EXITROOM' => self::MSGID_MASC_NOTI_EXITROOM,
            'MSGID_MASC_NOTI_KICKPLAYER' => self::MSGID_MASC_NOTI_KICKPLAYER,
            'MSGID_CMAS_REQ_INVITEPLAYER' => self::MSGID_CMAS_REQ_INVITEPLAYER,
            'MSGID_MASC_RESP_INVITEPLAYER' => self::MSGID_MASC_RESP_INVITEPLAYER,
            'MSGID_MASC_NOTI_INVITEPLAYER' => self::MSGID_MASC_NOTI_INVITEPLAYER,
            'MSGID_CMAS_REQ_ANSWERINVITE' => self::MSGID_CMAS_REQ_ANSWERINVITE,
            'MSGID_MASC_RESP_ANSWERINVITE' => self::MSGID_MASC_RESP_ANSWERINVITE,
            'MSGID_MASC_NOTI_ANSWERINVITE' => self::MSGID_MASC_NOTI_ANSWERINVITE,
            'MSGID_CMAS_REQ_TRACK' => self::MSGID_CMAS_REQ_TRACK,
            'MSGID_MASC_RESP_TRACK' => self::MSGID_MASC_RESP_TRACK,
            'MSGID_CMAS_REQ_ENTERHOUSE' => self::MSGID_CMAS_REQ_ENTERHOUSE,
            'MSGID_MASC_RESP_ENTERHOUSE' => self::MSGID_MASC_RESP_ENTERHOUSE,
            'MSGID_CMAS_REQ_ENTERSNSROOM' => self::MSGID_CMAS_REQ_ENTERSNSROOM,
            'MSGID_MASC_RESP_ENTERSNSROOM' => self::MSGID_MASC_RESP_ENTERSNSROOM,
            'MSGID_CMAS_REQ_FIXUPMATCH' => self::MSGID_CMAS_REQ_FIXUPMATCH,
            'MSGID_MASC_RESP_FIXUPMATCH' => self::MSGID_MASC_RESP_FIXUPMATCH,
            'MSGID_MASC_NOTI_FIXUPRESULT' => self::MSGID_MASC_NOTI_FIXUPRESULT,
            'MSGID_CMAS_REQ_GETROOMINFOBYROOMID' => self::MSGID_CMAS_REQ_GETROOMINFOBYROOMID,
            'MSGID_MASC_RESP_GETROOMINFOBYROOMID' => self::MSGID_MASC_RESP_GETROOMINFOBYROOMID,
            'MSGID_CMAS_REQ_GETMYWEDDINGROOM' => self::MSGID_CMAS_REQ_GETMYWEDDINGROOM,
            'MSGID_MASC_RESP_GETMYWEDDINGROOM' => self::MSGID_MASC_RESP_GETMYWEDDINGROOM,
        );
    }
}
}