<?php
/**
 * Auto generated from chatserver.proto at 2023-02-13 12:39:15
 */

namespace Xnhd\Core\Pb\Sdo {
/**
 * MSGID_CHATSERVER enum
 */
final class MSGID_CHATSERVER
{
    const MSGID_CCHS_REQ_MULTICASTCHAT = 2817;
    const MSGID_CHSC_RESP_MULTICASTCHAT = 35585;
    const MSGID_CCHS_REQ_BROADCASTCHAT = 2818;
    const MSGID_CHSC_RESP_BROADCASTCHAT = 35586;
    const MSGID_CHSC_NOTI_CHAT = 19203;
    const MSGID_CHSC_NOTI_BROADCASTCHAT = 19204;
    const MSGID_CCHS_REQ_SYSTEMCOMMONMSG = 2821;
    const MSGID_CHSC_RESP_SYSTEMCOMMONMSG = 35589;
    const MSGID_CHSC_NOTI_SYSTEMCOMMONMSG = 19205;
    const MSGID_CCHS_REQ_GETMSG = 2822;
    const MSGID_CHSC_RESP_GETMSG = 35590;
    const MSGID_CCHS_REQ_READMSG = 2823;
    const MSGID_CHSC_RESP_READMSG = 35591;
    const MSGID_CCHS_REQ_CENTERMULTICASTCHAT = 2824;
    const MSGID_CHSC_RESP_CENTERMULTICASTCHAT = 35592;
    const MSGID_CCHS_REQ_CENTERBROADCASTCHAT = 2825;
    const MSGID_CHSC_RESP_CENTERBROADCASTCHAT = 35593;
    const MSGID_CCHS_REQ_ANCHORTEXT = 2826;
    const MSGID_CHSC_RESP_ANCHORTEXT = 35594;
    const MSGID_CHSC_NOTI_ANCHORTEXT = 19210;
    const MSGID_CHSC_NOTI_ANCHORINFO = 19211;
    const MSGID_CCHS_REQ_LISTENANCHOR = 2828;
    const MSGID_CHSC_RESP_LISTENANCHOR = 35596;
    const MSGID_CHSC_NOTI_LISTENANCHOR = 19212;
    const MSGID_CCHS_REQ_ANCHORGIFT = 2829;
    const MSGID_CHSC_RESP_ANCHORGIFT = 35597;
    const MSGID_CHSC_NOTI_ANCHORGIFT = 19213;
    const MSGID_CCHS_REQ_BAN = 2832;
    const MSGID_CHSC_RESP_BAN = 35600;
    const MSGID_CHSC_NOTI_BAN = 19216;
    const MSGID_CCHS_REQ_CANCELBAN = 2833;
    const MSGID_CHSC_RESP_CANCELBAN = 35601;
    const MSGID_CHSC_NOTI_CANCELBAN = 19217;
    const MSGID_CCHS_REQ_GETBANLIST = 2834;
    const MSGID_CHSC_RESP_GETBANLIST = 35602;
    const MSGID_CCHS_REQ_PULLMESSAGE = 2835;
    const MSGID_CHSC_RESP_PULLMESSAGE = 35603;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'MSGID_CCHS_REQ_MULTICASTCHAT' => self::MSGID_CCHS_REQ_MULTICASTCHAT,
            'MSGID_CHSC_RESP_MULTICASTCHAT' => self::MSGID_CHSC_RESP_MULTICASTCHAT,
            'MSGID_CCHS_REQ_BROADCASTCHAT' => self::MSGID_CCHS_REQ_BROADCASTCHAT,
            'MSGID_CHSC_RESP_BROADCASTCHAT' => self::MSGID_CHSC_RESP_BROADCASTCHAT,
            'MSGID_CHSC_NOTI_CHAT' => self::MSGID_CHSC_NOTI_CHAT,
            'MSGID_CHSC_NOTI_BROADCASTCHAT' => self::MSGID_CHSC_NOTI_BROADCASTCHAT,
            'MSGID_CCHS_REQ_SYSTEMCOMMONMSG' => self::MSGID_CCHS_REQ_SYSTEMCOMMONMSG,
            'MSGID_CHSC_RESP_SYSTEMCOMMONMSG' => self::MSGID_CHSC_RESP_SYSTEMCOMMONMSG,
            'MSGID_CHSC_NOTI_SYSTEMCOMMONMSG' => self::MSGID_CHSC_NOTI_SYSTEMCOMMONMSG,
            'MSGID_CCHS_REQ_GETMSG' => self::MSGID_CCHS_REQ_GETMSG,
            'MSGID_CHSC_RESP_GETMSG' => self::MSGID_CHSC_RESP_GETMSG,
            'MSGID_CCHS_REQ_READMSG' => self::MSGID_CCHS_REQ_READMSG,
            'MSGID_CHSC_RESP_READMSG' => self::MSGID_CHSC_RESP_READMSG,
            'MSGID_CCHS_REQ_CENTERMULTICASTCHAT' => self::MSGID_CCHS_REQ_CENTERMULTICASTCHAT,
            'MSGID_CHSC_RESP_CENTERMULTICASTCHAT' => self::MSGID_CHSC_RESP_CENTERMULTICASTCHAT,
            'MSGID_CCHS_REQ_CENTERBROADCASTCHAT' => self::MSGID_CCHS_REQ_CENTERBROADCASTCHAT,
            'MSGID_CHSC_RESP_CENTERBROADCASTCHAT' => self::MSGID_CHSC_RESP_CENTERBROADCASTCHAT,
            'MSGID_CCHS_REQ_ANCHORTEXT' => self::MSGID_CCHS_REQ_ANCHORTEXT,
            'MSGID_CHSC_RESP_ANCHORTEXT' => self::MSGID_CHSC_RESP_ANCHORTEXT,
            'MSGID_CHSC_NOTI_ANCHORTEXT' => self::MSGID_CHSC_NOTI_ANCHORTEXT,
            'MSGID_CHSC_NOTI_ANCHORINFO' => self::MSGID_CHSC_NOTI_ANCHORINFO,
            'MSGID_CCHS_REQ_LISTENANCHOR' => self::MSGID_CCHS_REQ_LISTENANCHOR,
            'MSGID_CHSC_RESP_LISTENANCHOR' => self::MSGID_CHSC_RESP_LISTENANCHOR,
            'MSGID_CHSC_NOTI_LISTENANCHOR' => self::MSGID_CHSC_NOTI_LISTENANCHOR,
            'MSGID_CCHS_REQ_ANCHORGIFT' => self::MSGID_CCHS_REQ_ANCHORGIFT,
            'MSGID_CHSC_RESP_ANCHORGIFT' => self::MSGID_CHSC_RESP_ANCHORGIFT,
            'MSGID_CHSC_NOTI_ANCHORGIFT' => self::MSGID_CHSC_NOTI_ANCHORGIFT,
            'MSGID_CCHS_REQ_BAN' => self::MSGID_CCHS_REQ_BAN,
            'MSGID_CHSC_RESP_BAN' => self::MSGID_CHSC_RESP_BAN,
            'MSGID_CHSC_NOTI_BAN' => self::MSGID_CHSC_NOTI_BAN,
            'MSGID_CCHS_REQ_CANCELBAN' => self::MSGID_CCHS_REQ_CANCELBAN,
            'MSGID_CHSC_RESP_CANCELBAN' => self::MSGID_CHSC_RESP_CANCELBAN,
            'MSGID_CHSC_NOTI_CANCELBAN' => self::MSGID_CHSC_NOTI_CANCELBAN,
            'MSGID_CCHS_REQ_GETBANLIST' => self::MSGID_CCHS_REQ_GETBANLIST,
            'MSGID_CHSC_RESP_GETBANLIST' => self::MSGID_CHSC_RESP_GETBANLIST,
            'MSGID_CCHS_REQ_PULLMESSAGE' => self::MSGID_CCHS_REQ_PULLMESSAGE,
            'MSGID_CHSC_RESP_PULLMESSAGE' => self::MSGID_CHSC_RESP_PULLMESSAGE,
        );
    }
}
}