<?php
/**
 * Auto generated from searchserver.proto at 2023-02-13 12:39:19
 */

namespace Xnhd\Core\Pb\Sdo {
/**
 * MSGID_SEARCHSERVER enum
 */
final class MSGID_SEARCHSERVER
{
    const MSGID_CSHS_REQ_SEARCHGUILD = 5889;
    const MSGID_SHSC_RESP_SEARCHGUILD = 38657;
    const MSGID_CSHS_REQ_GETROLELISTINFO = 5904;
    const MSGID_SHSC_RESP_GETROLELISTINFO = 38672;
    const MSGID_CSHS_REQ_GETROLERANKINFO = 5905;
    const MSGID_SHSC_RESP_GETROLERANKINFO = 38673;
    const MSGID_CSHS_REQ_GETMUSICSCORE = 5906;
    const MSGID_SHSC_RESP_GETMUSICSCORE = 38674;
    const MSGID_CSHS_REQ_GETCUPRANKLIST = 5907;
    const MSGID_SHSC_RESP_GETCUPRANKLIST = 38675;
    const MSGID_CSHS_REQ_CHECKROLENAME = 5920;
    const MSGID_SHSC_RESP_CHECKROLENAME = 38688;
    const MSGID_CSHS_REQ_GETROLEIDBYNAME = 5921;
    const MSGID_SHSC_RESP_GETROLEIDBYNAME = 38689;
    const MSGID_CSHS_REQ_GETROLEINFOBYNAME = 5922;
    const MSGID_SHSC_RESP_GETROLEINFOBYNAME = 38690;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'MSGID_CSHS_REQ_SEARCHGUILD' => self::MSGID_CSHS_REQ_SEARCHGUILD,
            'MSGID_SHSC_RESP_SEARCHGUILD' => self::MSGID_SHSC_RESP_SEARCHGUILD,
            'MSGID_CSHS_REQ_GETROLELISTINFO' => self::MSGID_CSHS_REQ_GETROLELISTINFO,
            'MSGID_SHSC_RESP_GETROLELISTINFO' => self::MSGID_SHSC_RESP_GETROLELISTINFO,
            'MSGID_CSHS_REQ_GETROLERANKINFO' => self::MSGID_CSHS_REQ_GETROLERANKINFO,
            'MSGID_SHSC_RESP_GETROLERANKINFO' => self::MSGID_SHSC_RESP_GETROLERANKINFO,
            'MSGID_CSHS_REQ_GETMUSICSCORE' => self::MSGID_CSHS_REQ_GETMUSICSCORE,
            'MSGID_SHSC_RESP_GETMUSICSCORE' => self::MSGID_SHSC_RESP_GETMUSICSCORE,
            'MSGID_CSHS_REQ_GETCUPRANKLIST' => self::MSGID_CSHS_REQ_GETCUPRANKLIST,
            'MSGID_SHSC_RESP_GETCUPRANKLIST' => self::MSGID_SHSC_RESP_GETCUPRANKLIST,
            'MSGID_CSHS_REQ_CHECKROLENAME' => self::MSGID_CSHS_REQ_CHECKROLENAME,
            'MSGID_SHSC_RESP_CHECKROLENAME' => self::MSGID_SHSC_RESP_CHECKROLENAME,
            'MSGID_CSHS_REQ_GETROLEIDBYNAME' => self::MSGID_CSHS_REQ_GETROLEIDBYNAME,
            'MSGID_SHSC_RESP_GETROLEIDBYNAME' => self::MSGID_SHSC_RESP_GETROLEIDBYNAME,
            'MSGID_CSHS_REQ_GETROLEINFOBYNAME' => self::MSGID_CSHS_REQ_GETROLEINFOBYNAME,
            'MSGID_SHSC_RESP_GETROLEINFOBYNAME' => self::MSGID_SHSC_RESP_GETROLEINFOBYNAME,
        );
    }
}
}