<?php
/**
 * Auto generated from robotserver.proto at 2023-02-13 12:39:18
 */

namespace Xnhd\Core\Pb\Sdo {
/**
 * MSGID_ROBOTSERVER enum
 */
final class MSGID_ROBOTSERVER
{
    const MSGID_CROS_REQ_ADDROBOT = 3857;
    const MSGID_ROSC_RESP_ADDROBOT = 36625;
    const MSGID_CROS_REQ_REMOVEROBOT = 3858;
    const MSGID_ROSC_RESP_REMOVEROBOT = 36626;
    const MSGID_CROS_REQ_CONFIGROBOT = 4081;
    const MSGID_ROSC_RESP_CONFIGROBOT = 36849;
    const MSGID_ROSC_NOTI_STARTROBOT = 20466;
    const MSGID_ROSC_NOTI_STOPROBOT = 20467;
    const MSGID_ROSC_NOTI_STATERPTROBOT = 20468;
    const MSGID_ROSC_NOTI_STATEROBOT = 20469;
    const MSGID_ROSC_NOTI_UPLOADLOGSROBOT = 20470;
    const MSGID_CROS_REQ_STARTRECORDROBOT = 4087;
    const MSGID_ROSC_RESP_STARTRECORDROBOT = 36855;
    const MSGID_CROS_REQ_RECORDROBOT = 4088;
    const MSGID_ROSC_RESP_RECORDROBOT = 36856;
    const MSGID_CROS_REQ_ENDRECORDROBOT = 4089;
    const MSGID_ROSC_RESP_ENDRECORDROBOT = 36857;
    const MSGID_ROSC_NOTI_CLEARLOGSROBOT = 20474;
    const MSGID_ROSC_NOTI_USERPREFIXROBOT = 20475;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'MSGID_CROS_REQ_ADDROBOT' => self::MSGID_CROS_REQ_ADDROBOT,
            'MSGID_ROSC_RESP_ADDROBOT' => self::MSGID_ROSC_RESP_ADDROBOT,
            'MSGID_CROS_REQ_REMOVEROBOT' => self::MSGID_CROS_REQ_REMOVEROBOT,
            'MSGID_ROSC_RESP_REMOVEROBOT' => self::MSGID_ROSC_RESP_REMOVEROBOT,
            'MSGID_CROS_REQ_CONFIGROBOT' => self::MSGID_CROS_REQ_CONFIGROBOT,
            'MSGID_ROSC_RESP_CONFIGROBOT' => self::MSGID_ROSC_RESP_CONFIGROBOT,
            'MSGID_ROSC_NOTI_STARTROBOT' => self::MSGID_ROSC_NOTI_STARTROBOT,
            'MSGID_ROSC_NOTI_STOPROBOT' => self::MSGID_ROSC_NOTI_STOPROBOT,
            'MSGID_ROSC_NOTI_STATERPTROBOT' => self::MSGID_ROSC_NOTI_STATERPTROBOT,
            'MSGID_ROSC_NOTI_STATEROBOT' => self::MSGID_ROSC_NOTI_STATEROBOT,
            'MSGID_ROSC_NOTI_UPLOADLOGSROBOT' => self::MSGID_ROSC_NOTI_UPLOADLOGSROBOT,
            'MSGID_CROS_REQ_STARTRECORDROBOT' => self::MSGID_CROS_REQ_STARTRECORDROBOT,
            'MSGID_ROSC_RESP_STARTRECORDROBOT' => self::MSGID_ROSC_RESP_STARTRECORDROBOT,
            'MSGID_CROS_REQ_RECORDROBOT' => self::MSGID_CROS_REQ_RECORDROBOT,
            'MSGID_ROSC_RESP_RECORDROBOT' => self::MSGID_ROSC_RESP_RECORDROBOT,
            'MSGID_CROS_REQ_ENDRECORDROBOT' => self::MSGID_CROS_REQ_ENDRECORDROBOT,
            'MSGID_ROSC_RESP_ENDRECORDROBOT' => self::MSGID_ROSC_RESP_ENDRECORDROBOT,
            'MSGID_ROSC_NOTI_CLEARLOGSROBOT' => self::MSGID_ROSC_NOTI_CLEARLOGSROBOT,
            'MSGID_ROSC_NOTI_USERPREFIXROBOT' => self::MSGID_ROSC_NOTI_USERPREFIXROBOT,
        );
    }
}
}