<?php
/**
 * Auto generated from centerdataserver.proto at 2023-02-13 12:39:17
 */

namespace Xnhd\Core\Pb\Sdo {
/**
 * MSGID_CENTERDATASERVER enum
 */
final class MSGID_CENTERDATASERVER
{
    const MSGID_CCDS_REQ_GETROLEDATA = 5377;
    const MSGID_CDSC_RESP_GETROLEDATA = 38145;
    const MSGID_CCDS_REQ_GETACCOUNTDATA = 5378;
    const MSGID_CDSC_RESP_GETACCOUNTDATA = 38146;
    const MSGID_CCDS_REQ_GETAUCTIONSUM = 5392;
    const MSGID_CDSC_RESP_GETAUCTIONSUM = 38160;
    const MSGID_CCDS_REQ_GETAUCTIONLIST = 5393;
    const MSGID_CDSC_RESP_GETAUCTIONLIST = 38161;
    const MSGID_CCDS_REQ_GETROLEAUCTION = 5394;
    const MSGID_CDSC_RESP_GETROLEAUCTION = 38162;
    const MSGID_CCDS_REQ_ONSALEAUCTION = 5395;
    const MSGID_CDSC_RESP_ONSALEAUCTION = 38163;
    const MSGID_CCDS_REQ_CANCELAUCTION = 5396;
    const MSGID_CDSC_RESP_CANCELAUCTION = 38164;
    const MSGID_CCDS_REQ_BID = 5397;
    const MSGID_CDSC_RESP_BID = 38165;
    const MSGID_PDBC_NOTI_BIDRESULT = 21781;
    const MSGID_CCDS_REQ_GETAUCTIONRECORD = 5398;
    const MSGID_CDSC_RESP_GETAUCTIONRECORD = 38166;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'MSGID_CCDS_REQ_GETROLEDATA' => self::MSGID_CCDS_REQ_GETROLEDATA,
            'MSGID_CDSC_RESP_GETROLEDATA' => self::MSGID_CDSC_RESP_GETROLEDATA,
            'MSGID_CCDS_REQ_GETACCOUNTDATA' => self::MSGID_CCDS_REQ_GETACCOUNTDATA,
            'MSGID_CDSC_RESP_GETACCOUNTDATA' => self::MSGID_CDSC_RESP_GETACCOUNTDATA,
            'MSGID_CCDS_REQ_GETAUCTIONSUM' => self::MSGID_CCDS_REQ_GETAUCTIONSUM,
            'MSGID_CDSC_RESP_GETAUCTIONSUM' => self::MSGID_CDSC_RESP_GETAUCTIONSUM,
            'MSGID_CCDS_REQ_GETAUCTIONLIST' => self::MSGID_CCDS_REQ_GETAUCTIONLIST,
            'MSGID_CDSC_RESP_GETAUCTIONLIST' => self::MSGID_CDSC_RESP_GETAUCTIONLIST,
            'MSGID_CCDS_REQ_GETROLEAUCTION' => self::MSGID_CCDS_REQ_GETROLEAUCTION,
            'MSGID_CDSC_RESP_GETROLEAUCTION' => self::MSGID_CDSC_RESP_GETROLEAUCTION,
            'MSGID_CCDS_REQ_ONSALEAUCTION' => self::MSGID_CCDS_REQ_ONSALEAUCTION,
            'MSGID_CDSC_RESP_ONSALEAUCTION' => self::MSGID_CDSC_RESP_ONSALEAUCTION,
            'MSGID_CCDS_REQ_CANCELAUCTION' => self::MSGID_CCDS_REQ_CANCELAUCTION,
            'MSGID_CDSC_RESP_CANCELAUCTION' => self::MSGID_CDSC_RESP_CANCELAUCTION,
            'MSGID_CCDS_REQ_BID' => self::MSGID_CCDS_REQ_BID,
            'MSGID_CDSC_RESP_BID' => self::MSGID_CDSC_RESP_BID,
            'MSGID_PDBC_NOTI_BIDRESULT' => self::MSGID_PDBC_NOTI_BIDRESULT,
            'MSGID_CCDS_REQ_GETAUCTIONRECORD' => self::MSGID_CCDS_REQ_GETAUCTIONRECORD,
            'MSGID_CDSC_RESP_GETAUCTIONRECORD' => self::MSGID_CDSC_RESP_GETAUCTIONRECORD,
        );
    }
}
}