<?php
/**
 * Auto generated from define.proto at 2023-02-13 12:39:22
 */

namespace Xnhd\Core\Pb\Sdo {
/**
 * ParamType enum
 */
final class ParamType
{
    const enmParamType_None = 0;
    const enmParamType_Level = 10001;
    const enmParamType_ActiveDayPoint = 10002;
    const enmParamType_ActiveWeekPoint = 10003;
    const enmParamType_NewPlayerPoint = 10004;
    const enmParamType_DownLoad = 10005;
    const enmParamType_LevelCrown = 10011;
    const enmParamType_QA = 11000;
    const enmParamType_CompleteDailyTask = 11001;
    const enmParamType_CompleteHouseTask = 11002;
    const enmParamType_CompleteTourTask = 11003;
    const enmParamType_QA2 = 11004;
    const enmParamType_QA3 = 11005;
    const enmParamType_UploadPic = 20001;
    const enmParamType_VoiceCard = 20002;
    const enmParamType_SetBirthday = 20003;
    const enmParamType_SetCity = 20004;
    const enmParamType_SetSigneture = 20005;
    const enmParamType_SetLabel = 20006;
    const enmParamType_RolePersonFace = 20007;
    const enmParamType_Pay_Source = 30000;
    const enmParamType_UseGCoin = 30001;
    const enmParamType_UseGCoin_Source = 30002;
    const enmParamType_TotalUseGCoin_Source = 30003;
    const enmParamType_UseScore = 30004;
    const enmParamType_UseScore_Source = 30005;
    const enmParamType_TotalUseScore_Source = 30006;
    const enmParamType_UseMoney = 30007;
    const enmParamType_UseMoney_Source = 30008;
    const enmParamType_TotalUseMoney_Source = 30009;
    const enmParamType_UseHCoin = 30010;
    const enmParamType_UseHCoin_Source = 30011;
    const enmParamType_TotalUseHCoin_Source = 30012;
    const enmParamType_HCoinExchangeGCoin = 30013;
    const enmParamType_GetMoney = 30014;
    const enmParamType_GetMoney_Source = 30015;
    const enmParamType_TotalGetMoney_Source = 30016;
    const enmParamType_TotalPay = 30020;
    const enmParamType_TotalPayYuan = 30021;
    const enmParamType_MonthCardPrize = 30022;
    const enmParamType_BlackCradPrize = 30023;
    const enmParamType_CrownDayPrize = 30024;
    const enmParamType_CrownMonthPrize = 30025;
    const enmParamType_VipLevelPrize = 30026;
    const enmParamType_VipWeekPrize = 30027;
    const enmParamType_MallBuy = 30100;
    const enmParamType_MallCloth = 30101;
    const enmParamType_MallBeauty = 30102;
    const enmParamType_Item_Add_Source = 31000;
    const enmParamType_Item_Donate = 31001;
    const enmParamType_GetCloth = 31002;
    const enmParamType_ScoreCloth = 31003;
    const enmParamType_CommentCloth = 31004;
    const enmParamType_PutOnCloth = 31005;
    const enmParamType_ItemBook_Score = 31006;
    const enmParamType_ItemBook_Score_50 = 31007;
    const enmParamType_ItemBook_SuitCount = 31008;
    const enmParamType_UseItem_5217 = 31009;
    const enmParamType_UseItem = 31010;
    const enmParamType_Raffle_Treasure = 31011;
    const enmParamType_UseItem_6003 = 31012;
    const enmParamType_AddItem_5202 = 31013;
    const enmParamType_BestPrize_Raffle = 31014;
    const enmParamType_LuckCityBox = 31015;
    const enmParamType_Raffle_BoxPray = 31016;
    const enmParamType_Item_Add_ItemID = 31017;
    const enmParamType_Raffle_StarCall = 31018;
    const enmParamType_Item_Add_5228 = 31019;
    const enmParamType_Item_Add_5229 = 31020;
    const enmParamType_Item_Add_574Or20014 = 31021;
    const enmParamType_Item_Add_575Or20015 = 31022;
    const enmParamType_Item_Add_576Or20016 = 31023;
    const enmParamType_More_Score = 40000;
    const enmParamType_More_Combo = 40001;
    const enmParamType_More_Grade = 40002;
    const enmParamType_Less_Miss = 40003;
    const enmParamType_More_Accuracy = 40004;
    const enmParamType_More_SPerfect = 40005;
    const enmParamType_More_Perfect = 40006;
    const enmParamType_More_CSPerfect = 40007;
    const enmParamType_AllCombo = 40008;
    const enmParamType_AllPerfect = 40009;
    const enmParamType_AllSPerfect = 40010;
    const enmParamType_Equal_Great = 40011;
    const enmParamType_Equal_SPerfect = 40012;
    const enmParamType_Equal_Perfect = 40013;
    const enmParamType_ScoreContain_X_Y = 40014;
    const enmParamType_ScoreContain_X_Y_Z = 40015;
    const enmParamType_ScoreContain_XYs = 40016;
    const enmParamType_ScoreEnd_X = 40017;
    const enmParamType_More_CPerfect = 40018;
    const enmParamType_More_Combo_GamePlay = 40019;
    const enmParamType_Dance_Source = 40101;
    const enmParamType_DanceRoom = 40102;
    const enmParamType_DanceRoomTeam = 40103;
    const enmParamType_DanceAmateur = 40104;
    const enmParamType_DanceAmateurTeam = 40105;
    const enmParamType_DanceTour = 40106;
    const enmParamType_DanceChanllenge = 40107;
    const enmParamType_DanceTourChanllenge = 40108;
    const enmParamType_DanceQualify = 40109;
    const enmParamType_DanceQualifyTeam = 40110;
    const enmParamType_DanceSongRank = 40111;
    const enmParamType_Dance_GamePlay = 40200;
    const enmParamType_DanceDropBall = 40201;
    const enmParamType_DanceAU = 40202;
    const enmParamType_DanceHeartStar = 40203;
    const enmParamType_DanceLM = 40204;
    const enmParamType_Normal_More_Grade = 40205;
    const enmParamType_Hard_More_Grade = 40206;
    const enmParamType_Dance_GameMode = 40300;
    const enmParamType_DanceTeam = 40301;
    const enmParamType_Win_Source = 40400;
    const enmParamType_QualifyWin = 40401;
    const enmParamType_Win_Team = 40402;
    const enmParamType_OneDanceCombo_DropBall = 40403;
    const enmParamType_OneDancePerfect_HeartStar = 40404;
    const enmParamType_DanceCount = 40500;
    const enmParamType_DanceMulPlayer = 40501;
    const enmParamType_4Dance_Rank_2nd = 40502;
    const enmParamType_DanceGradeA = 40503;
    const enmParamType_DanceFourPlayer = 40504;
    const enmParamType_DanceFourPlayerRank2 = 40505;
    const enmParamType_DanceFourPlayerRank1 = 40506;
    const enmParamType_DanceFriend = 40507;
    const enmParamType_DanceTotalScore = 40508;
    const enmParamType_DanceTotalCombo = 40509;
    const enmParamType_DanceTotalSP = 40510;
    const enmParamType_DanceDropTotalP = 40511;
    const enmParamType_DanceStarTotalP = 40512;
    const enmParamType_DanceLMTotalP = 40513;
    const enmParamType_DanceDropTotalSP = 40514;
    const enmParamType_DanceNormalLevel = 40515;
    const enmParamType_DanceStar8SS = 40516;
    const enmParamType_DanceStar9SSS = 40517;
    const enmParamType_DanceSSS = 40518;
    const enmParamType_DanceHardMaxCombo = 40519;
    const enmParamType_DanceNormalTotalSP = 40520;
    const enmParamType_DanceMaxCombo = 40521;
    const enmParamType_DanceNormalSSS = 40522;
    const enmParamType_QualifyDropBall = 40523;
    const enmParamType_QualifyStar = 40524;
    const enmParamType_DanceSPCount = 40525;
    const enmParamType_QualifyWinDropBall = 40526;
    const enmParamType_QualifyWinStar = 40527;
    const enmParamType_DanceDropGradeA = 40528;
    const enmParamType_DanceStarGradeA = 40529;
    const enmParamType_DanceLMGradeA = 40530;
    const enmParamType_DanceRBGradeA = 40531;
    const enmParamType_DanceGradeS = 40532;
    const enmParamType_DanceGradeSS = 40533;
    const enmParamType_DanceHardSSS = 40534;
    const enmParamType_DanceAC = 40535;
    const enmParamType_DanceAP = 40536;
    const enmParamType_Dance_Star3 = 40537;
    const enmParamType_Dance_Hall = 40538;
    const enmParamType_CreateRoom = 41000;
    const enmParamType_JoinRoom = 41001;
    const enmParamType_InviteRoom = 41002;
    const enmParamType_RoomAction = 41003;
    const enmParamType_PassTour = 42000;
    const enmParamType_PassTour_110004 = 42001;
    const enmParamType_PassTour_110012 = 42002;
    const enmParamType_PassTour_110018 = 42003;
    const enmParamType_PassTour_110024 = 42004;
    const enmParamType_PassTour_110030 = 42005;
    const enmParamType_PassTour_110036 = 42006;
    const enmParamType_PassTour_110042 = 42007;
    const enmParamType_PassTour_110048 = 42008;
    const enmParamType_PassTour_110054 = 42009;
    const enmParamType_PassTour_110060 = 42010;
    const enmParamType_Tour_Part = 42100;
    const enmParamType_Tour_Part_10 = 42101;
    const enmParamType_TreeKey_Collect = 42200;
    const enmParamType_TreeKey_Collect_3 = 42201;
    const enmParamType_CupCopper_Normal = 43000;
    const enmParamType_CupSilver_Normal = 43001;
    const enmParamType_CupGold_Normal = 43002;
    const enmParamType_CupPlatinum_Normal = 43003;
    const enmParamType_CupCopper_Hard = 43004;
    const enmParamType_CupSilver_Hard = 43005;
    const enmParamType_CupGold_Hard = 43006;
    const enmParamType_CupPlatinum_Hard = 43007;
    const enmParamType_CupCopper_GamePlay = 43008;
    const enmParamType_CupSilver_GamePlay = 43009;
    const enmParamType_CupGold_GamePlay = 43010;
    const enmParamType_CupPlatinum_GamePlay = 43011;
    const enmParamType_CupSilver = 43012;
    const enmParamType_CupGold = 43013;
    const enmParamType_CupPlatinum = 43014;
    const enmParamType_Qualify_Title = 44000;
    const enmParamType_Qualify_Title_Rank2 = 44001;
    const enmParamType_Qualify_Title_Rank3 = 44002;
    const enmParamType_Qualify_Title_Rank4 = 44003;
    const enmParamType_Qualify_Title_Rank5 = 44004;
    const enmParamType_Qualify_Title_Rank03 = 44005;
    const enmParamType_Qualify_Title_Rank13 = 44006;
    const enmParamType_Qualify_Title_Rank23 = 44007;
    const enmParamType_Follow_Count = 50000;
    const enmParamType_FansCount = 50001;
    const enmParamType_Friend_Count = 50002;
    const enmParamType_Friend_Favorability = 50003;
    const enmParamType_SendFriend = 50004;
    const enmParamType_SendGift = 50005;
    const enmParamType_ReceiveGift = 50006;
    const enmParamType_SendFameTotal = 50007;
    const enmParamType_VisitHomePage = 50008;
    const enmParamType_LikeHomePage = 50009;
    const enmParamType_BeLikeHomePage = 50010;
    const enmParamType_BigSpeaker = 51000;
    const enmParamType_InSNSRoom_Enter = 52000;
    const enmParamType_InSNSRoom_Time = 52001;
    const enmParamType_SNSRoom_NPC = 52002;
    const enmParamType_SNSRoom_Game = 52003;
    const enmParamType_SNSRoom_Ball = 52004;
    const enmParamType_SNSRoom_Blind = 52005;
    const enmParamType_SNSRoom_Exchange = 52006;
    const enmParamType_SNSRoom_Play = 52007;
    const enmParamType_SNSRoom_PlayWheel = 52008;
    const enmParamType_SNSRoom_PlayBoat = 52009;
    const enmParamType_Meet = 53000;
    const enmParamType_Confession = 53001;
    const enmParamType_Lover = 53002;
    const enmParamType_LoverToken = 53003;
    const enmParamType_SNSRoom_Experence = 53004;
    const enmParamType_InSNSRoom_SwimPool = 53005;
    const enmParamType_InSNSRoom_Drink = 53006;
    const enmParamType_InSNSRoom_SwimPool_Time = 53007;
    const enmParamType_House_EnterMyHouse = 60000;
    const enmParamType_House_Level = 60001;
    const enmParamType_House_Level_3 = 60002;
    const enmParamType_House_GetExperence = 60003;
    const enmParamType_House_Dress_Count = 60010;
    const enmParamType_House_Luxury = 60011;
    const enmParamType_House_Dress = 60012;
    const enmParamType_House_Make = 60013;
    const enmParamType_House_Buy_Furniture = 60014;
    const enmParamType_House_EnterZone = 60015;
    const enmParamType_House_DressZone = 60016;
    const enmParamType_House_DressItem = 60017;
    const enmParamType_House_LuxuryZone = 60018;
    const enmParamType_House_CreateRoom = 60100;
    const enmParamType_House_Dance = 60101;
    const enmParamType_House_Invite = 60102;
    const enmParamType_House_Visit = 60103;
    const enmParamType_House_Like = 60104;
    const enmParamType_House_BeLike = 60105;
    const enmParamType_House_Merge = 60200;
    const enmParamType_House_Merge_Lv = 60201;
    const enmParamType_House_Produce = 60202;
    const enmParamType_House_Stamina_Cost = 60203;
    const enmParamType_House_Stamina_Add = 60204;
    const enmParamType_House_Task_Daily = 60205;
    const enmParamType_House_Merge_Level7 = 60206;
    const enmParamType_House_Merge_Level10 = 60207;
    const enmParamType_LoginCnt = 70000;
    const enmParamType_LoginMonth = 70001;
    const enmParamType_OnlineTime = 70002;
    const enmParamType_TodayTimePeriod_12_14 = 70003;
    const enmParamType_TodayTimePeriod_19_21 = 70004;
    const enmParamType_SignCnt = 70005;
    const enmParamType_Challenge_Pass = 70006;
    const enmParamType_JigsawPuzzle = 70007;
    const enmParamType_FireWorksWish = 70008;
    const enmParamType_FireWorksBeLiked = 70009;
    const enmParamType_WishFree = 70010;
    const enmParamType_WishBuyBoxCount = 70011;
    const enmParamType_BPActive = 70012;
    const enmParamType_BPLevel = 70013;
    const enmParamType_BPPayment = 70014;
    const enmParamType_MergeLineSection = 70015;
    const enmParamType_DanceDropGet = 70016;
    const enmParamType_UseItem6035 = 70017;
    const enmParamType_GetItem10111 = 70018;
    const enmParamType_GetItem1 = 70019;
    const enmParamType_GetItem2 = 70020;
    const enmParamType_GetItem3 = 70021;
    const enmParamType_GetItem4 = 70022;
    const enmParamType_GetItem5 = 70023;
    const enmParamType_GetItem6 = 70024;
    const enmParamType_GetItem7 = 70025;
    const enmParamType_GetItem8 = 70026;
    const enmParamType_WishBuy = 70027;
    const enmParamType_WishUseTotal = 70028;
    const enmParamType_BuySecretBox = 70029;
    const enmParamType_LoginCntAfterBuyBox = 70030;
    const enmParamType_GetItem6034 = 70031;
    const enmParamType_Couple_Be = 80000;
    const enmParamType_Couple_Camera = 80001;
    const enmParamType_Couple_Ferris = 80002;
    const enmParamType_Couple_Yacht = 80003;
    const enmParamType_Couple_Medal = 80004;
    const enmParamType_Couple_Raise = 80005;
    const enmParamType_Couple_Chat = 80006;
    const enmParamType_HonourAcc = 90000;
    const enmParamType_DanceDropBall_SSS = 90001;
    const enmParamType_DanceHeartStar_SSS = 90002;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'enmParamType_None' => self::enmParamType_None,
            'enmParamType_Level' => self::enmParamType_Level,
            'enmParamType_ActiveDayPoint' => self::enmParamType_ActiveDayPoint,
            'enmParamType_ActiveWeekPoint' => self::enmParamType_ActiveWeekPoint,
            'enmParamType_NewPlayerPoint' => self::enmParamType_NewPlayerPoint,
            'enmParamType_DownLoad' => self::enmParamType_DownLoad,
            'enmParamType_LevelCrown' => self::enmParamType_LevelCrown,
            'enmParamType_QA' => self::enmParamType_QA,
            'enmParamType_CompleteDailyTask' => self::enmParamType_CompleteDailyTask,
            'enmParamType_CompleteHouseTask' => self::enmParamType_CompleteHouseTask,
            'enmParamType_CompleteTourTask' => self::enmParamType_CompleteTourTask,
            'enmParamType_QA2' => self::enmParamType_QA2,
            'enmParamType_QA3' => self::enmParamType_QA3,
            'enmParamType_UploadPic' => self::enmParamType_UploadPic,
            'enmParamType_VoiceCard' => self::enmParamType_VoiceCard,
            'enmParamType_SetBirthday' => self::enmParamType_SetBirthday,
            'enmParamType_SetCity' => self::enmParamType_SetCity,
            'enmParamType_SetSigneture' => self::enmParamType_SetSigneture,
            'enmParamType_SetLabel' => self::enmParamType_SetLabel,
            'enmParamType_RolePersonFace' => self::enmParamType_RolePersonFace,
            'enmParamType_Pay_Source' => self::enmParamType_Pay_Source,
            'enmParamType_UseGCoin' => self::enmParamType_UseGCoin,
            'enmParamType_UseGCoin_Source' => self::enmParamType_UseGCoin_Source,
            'enmParamType_TotalUseGCoin_Source' => self::enmParamType_TotalUseGCoin_Source,
            'enmParamType_UseScore' => self::enmParamType_UseScore,
            'enmParamType_UseScore_Source' => self::enmParamType_UseScore_Source,
            'enmParamType_TotalUseScore_Source' => self::enmParamType_TotalUseScore_Source,
            'enmParamType_UseMoney' => self::enmParamType_UseMoney,
            'enmParamType_UseMoney_Source' => self::enmParamType_UseMoney_Source,
            'enmParamType_TotalUseMoney_Source' => self::enmParamType_TotalUseMoney_Source,
            'enmParamType_UseHCoin' => self::enmParamType_UseHCoin,
            'enmParamType_UseHCoin_Source' => self::enmParamType_UseHCoin_Source,
            'enmParamType_TotalUseHCoin_Source' => self::enmParamType_TotalUseHCoin_Source,
            'enmParamType_HCoinExchangeGCoin' => self::enmParamType_HCoinExchangeGCoin,
            'enmParamType_GetMoney' => self::enmParamType_GetMoney,
            'enmParamType_GetMoney_Source' => self::enmParamType_GetMoney_Source,
            'enmParamType_TotalGetMoney_Source' => self::enmParamType_TotalGetMoney_Source,
            'enmParamType_TotalPay' => self::enmParamType_TotalPay,
            'enmParamType_TotalPayYuan' => self::enmParamType_TotalPayYuan,
            'enmParamType_MonthCardPrize' => self::enmParamType_MonthCardPrize,
            'enmParamType_BlackCradPrize' => self::enmParamType_BlackCradPrize,
            'enmParamType_CrownDayPrize' => self::enmParamType_CrownDayPrize,
            'enmParamType_CrownMonthPrize' => self::enmParamType_CrownMonthPrize,
            'enmParamType_VipLevelPrize' => self::enmParamType_VipLevelPrize,
            'enmParamType_VipWeekPrize' => self::enmParamType_VipWeekPrize,
            'enmParamType_MallBuy' => self::enmParamType_MallBuy,
            'enmParamType_MallCloth' => self::enmParamType_MallCloth,
            'enmParamType_MallBeauty' => self::enmParamType_MallBeauty,
            'enmParamType_Item_Add_Source' => self::enmParamType_Item_Add_Source,
            'enmParamType_Item_Donate' => self::enmParamType_Item_Donate,
            'enmParamType_GetCloth' => self::enmParamType_GetCloth,
            'enmParamType_ScoreCloth' => self::enmParamType_ScoreCloth,
            'enmParamType_CommentCloth' => self::enmParamType_CommentCloth,
            'enmParamType_PutOnCloth' => self::enmParamType_PutOnCloth,
            'enmParamType_ItemBook_Score' => self::enmParamType_ItemBook_Score,
            'enmParamType_ItemBook_Score_50' => self::enmParamType_ItemBook_Score_50,
            'enmParamType_ItemBook_SuitCount' => self::enmParamType_ItemBook_SuitCount,
            'enmParamType_UseItem_5217' => self::enmParamType_UseItem_5217,
            'enmParamType_UseItem' => self::enmParamType_UseItem,
            'enmParamType_Raffle_Treasure' => self::enmParamType_Raffle_Treasure,
            'enmParamType_UseItem_6003' => self::enmParamType_UseItem_6003,
            'enmParamType_AddItem_5202' => self::enmParamType_AddItem_5202,
            'enmParamType_BestPrize_Raffle' => self::enmParamType_BestPrize_Raffle,
            'enmParamType_LuckCityBox' => self::enmParamType_LuckCityBox,
            'enmParamType_Raffle_BoxPray' => self::enmParamType_Raffle_BoxPray,
            'enmParamType_Item_Add_ItemID' => self::enmParamType_Item_Add_ItemID,
            'enmParamType_Raffle_StarCall' => self::enmParamType_Raffle_StarCall,
            'enmParamType_Item_Add_5228' => self::enmParamType_Item_Add_5228,
            'enmParamType_Item_Add_5229' => self::enmParamType_Item_Add_5229,
            'enmParamType_Item_Add_574Or20014' => self::enmParamType_Item_Add_574Or20014,
            'enmParamType_Item_Add_575Or20015' => self::enmParamType_Item_Add_575Or20015,
            'enmParamType_Item_Add_576Or20016' => self::enmParamType_Item_Add_576Or20016,
            'enmParamType_More_Score' => self::enmParamType_More_Score,
            'enmParamType_More_Combo' => self::enmParamType_More_Combo,
            'enmParamType_More_Grade' => self::enmParamType_More_Grade,
            'enmParamType_Less_Miss' => self::enmParamType_Less_Miss,
            'enmParamType_More_Accuracy' => self::enmParamType_More_Accuracy,
            'enmParamType_More_SPerfect' => self::enmParamType_More_SPerfect,
            'enmParamType_More_Perfect' => self::enmParamType_More_Perfect,
            'enmParamType_More_CSPerfect' => self::enmParamType_More_CSPerfect,
            'enmParamType_AllCombo' => self::enmParamType_AllCombo,
            'enmParamType_AllPerfect' => self::enmParamType_AllPerfect,
            'enmParamType_AllSPerfect' => self::enmParamType_AllSPerfect,
            'enmParamType_Equal_Great' => self::enmParamType_Equal_Great,
            'enmParamType_Equal_SPerfect' => self::enmParamType_Equal_SPerfect,
            'enmParamType_Equal_Perfect' => self::enmParamType_Equal_Perfect,
            'enmParamType_ScoreContain_X_Y' => self::enmParamType_ScoreContain_X_Y,
            'enmParamType_ScoreContain_X_Y_Z' => self::enmParamType_ScoreContain_X_Y_Z,
            'enmParamType_ScoreContain_XYs' => self::enmParamType_ScoreContain_XYs,
            'enmParamType_ScoreEnd_X' => self::enmParamType_ScoreEnd_X,
            'enmParamType_More_CPerfect' => self::enmParamType_More_CPerfect,
            'enmParamType_More_Combo_GamePlay' => self::enmParamType_More_Combo_GamePlay,
            'enmParamType_Dance_Source' => self::enmParamType_Dance_Source,
            'enmParamType_DanceRoom' => self::enmParamType_DanceRoom,
            'enmParamType_DanceRoomTeam' => self::enmParamType_DanceRoomTeam,
            'enmParamType_DanceAmateur' => self::enmParamType_DanceAmateur,
            'enmParamType_DanceAmateurTeam' => self::enmParamType_DanceAmateurTeam,
            'enmParamType_DanceTour' => self::enmParamType_DanceTour,
            'enmParamType_DanceChanllenge' => self::enmParamType_DanceChanllenge,
            'enmParamType_DanceTourChanllenge' => self::enmParamType_DanceTourChanllenge,
            'enmParamType_DanceQualify' => self::enmParamType_DanceQualify,
            'enmParamType_DanceQualifyTeam' => self::enmParamType_DanceQualifyTeam,
            'enmParamType_DanceSongRank' => self::enmParamType_DanceSongRank,
            'enmParamType_Dance_GamePlay' => self::enmParamType_Dance_GamePlay,
            'enmParamType_DanceDropBall' => self::enmParamType_DanceDropBall,
            'enmParamType_DanceAU' => self::enmParamType_DanceAU,
            'enmParamType_DanceHeartStar' => self::enmParamType_DanceHeartStar,
            'enmParamType_DanceLM' => self::enmParamType_DanceLM,
            'enmParamType_Normal_More_Grade' => self::enmParamType_Normal_More_Grade,
            'enmParamType_Hard_More_Grade' => self::enmParamType_Hard_More_Grade,
            'enmParamType_Dance_GameMode' => self::enmParamType_Dance_GameMode,
            'enmParamType_DanceTeam' => self::enmParamType_DanceTeam,
            'enmParamType_Win_Source' => self::enmParamType_Win_Source,
            'enmParamType_QualifyWin' => self::enmParamType_QualifyWin,
            'enmParamType_Win_Team' => self::enmParamType_Win_Team,
            'enmParamType_OneDanceCombo_DropBall' => self::enmParamType_OneDanceCombo_DropBall,
            'enmParamType_OneDancePerfect_HeartStar' => self::enmParamType_OneDancePerfect_HeartStar,
            'enmParamType_DanceCount' => self::enmParamType_DanceCount,
            'enmParamType_DanceMulPlayer' => self::enmParamType_DanceMulPlayer,
            'enmParamType_4Dance_Rank_2nd' => self::enmParamType_4Dance_Rank_2nd,
            'enmParamType_DanceGradeA' => self::enmParamType_DanceGradeA,
            'enmParamType_DanceFourPlayer' => self::enmParamType_DanceFourPlayer,
            'enmParamType_DanceFourPlayerRank2' => self::enmParamType_DanceFourPlayerRank2,
            'enmParamType_DanceFourPlayerRank1' => self::enmParamType_DanceFourPlayerRank1,
            'enmParamType_DanceFriend' => self::enmParamType_DanceFriend,
            'enmParamType_DanceTotalScore' => self::enmParamType_DanceTotalScore,
            'enmParamType_DanceTotalCombo' => self::enmParamType_DanceTotalCombo,
            'enmParamType_DanceTotalSP' => self::enmParamType_DanceTotalSP,
            'enmParamType_DanceDropTotalP' => self::enmParamType_DanceDropTotalP,
            'enmParamType_DanceStarTotalP' => self::enmParamType_DanceStarTotalP,
            'enmParamType_DanceLMTotalP' => self::enmParamType_DanceLMTotalP,
            'enmParamType_DanceDropTotalSP' => self::enmParamType_DanceDropTotalSP,
            'enmParamType_DanceNormalLevel' => self::enmParamType_DanceNormalLevel,
            'enmParamType_DanceStar8SS' => self::enmParamType_DanceStar8SS,
            'enmParamType_DanceStar9SSS' => self::enmParamType_DanceStar9SSS,
            'enmParamType_DanceSSS' => self::enmParamType_DanceSSS,
            'enmParamType_DanceHardMaxCombo' => self::enmParamType_DanceHardMaxCombo,
            'enmParamType_DanceNormalTotalSP' => self::enmParamType_DanceNormalTotalSP,
            'enmParamType_DanceMaxCombo' => self::enmParamType_DanceMaxCombo,
            'enmParamType_DanceNormalSSS' => self::enmParamType_DanceNormalSSS,
            'enmParamType_QualifyDropBall' => self::enmParamType_QualifyDropBall,
            'enmParamType_QualifyStar' => self::enmParamType_QualifyStar,
            'enmParamType_DanceSPCount' => self::enmParamType_DanceSPCount,
            'enmParamType_QualifyWinDropBall' => self::enmParamType_QualifyWinDropBall,
            'enmParamType_QualifyWinStar' => self::enmParamType_QualifyWinStar,
            'enmParamType_DanceDropGradeA' => self::enmParamType_DanceDropGradeA,
            'enmParamType_DanceStarGradeA' => self::enmParamType_DanceStarGradeA,
            'enmParamType_DanceLMGradeA' => self::enmParamType_DanceLMGradeA,
            'enmParamType_DanceRBGradeA' => self::enmParamType_DanceRBGradeA,
            'enmParamType_DanceGradeS' => self::enmParamType_DanceGradeS,
            'enmParamType_DanceGradeSS' => self::enmParamType_DanceGradeSS,
            'enmParamType_DanceHardSSS' => self::enmParamType_DanceHardSSS,
            'enmParamType_DanceAC' => self::enmParamType_DanceAC,
            'enmParamType_DanceAP' => self::enmParamType_DanceAP,
            'enmParamType_Dance_Star3' => self::enmParamType_Dance_Star3,
            'enmParamType_Dance_Hall' => self::enmParamType_Dance_Hall,
            'enmParamType_CreateRoom' => self::enmParamType_CreateRoom,
            'enmParamType_JoinRoom' => self::enmParamType_JoinRoom,
            'enmParamType_InviteRoom' => self::enmParamType_InviteRoom,
            'enmParamType_RoomAction' => self::enmParamType_RoomAction,
            'enmParamType_PassTour' => self::enmParamType_PassTour,
            'enmParamType_PassTour_110004' => self::enmParamType_PassTour_110004,
            'enmParamType_PassTour_110012' => self::enmParamType_PassTour_110012,
            'enmParamType_PassTour_110018' => self::enmParamType_PassTour_110018,
            'enmParamType_PassTour_110024' => self::enmParamType_PassTour_110024,
            'enmParamType_PassTour_110030' => self::enmParamType_PassTour_110030,
            'enmParamType_PassTour_110036' => self::enmParamType_PassTour_110036,
            'enmParamType_PassTour_110042' => self::enmParamType_PassTour_110042,
            'enmParamType_PassTour_110048' => self::enmParamType_PassTour_110048,
            'enmParamType_PassTour_110054' => self::enmParamType_PassTour_110054,
            'enmParamType_PassTour_110060' => self::enmParamType_PassTour_110060,
            'enmParamType_Tour_Part' => self::enmParamType_Tour_Part,
            'enmParamType_Tour_Part_10' => self::enmParamType_Tour_Part_10,
            'enmParamType_TreeKey_Collect' => self::enmParamType_TreeKey_Collect,
            'enmParamType_TreeKey_Collect_3' => self::enmParamType_TreeKey_Collect_3,
            'enmParamType_CupCopper_Normal' => self::enmParamType_CupCopper_Normal,
            'enmParamType_CupSilver_Normal' => self::enmParamType_CupSilver_Normal,
            'enmParamType_CupGold_Normal' => self::enmParamType_CupGold_Normal,
            'enmParamType_CupPlatinum_Normal' => self::enmParamType_CupPlatinum_Normal,
            'enmParamType_CupCopper_Hard' => self::enmParamType_CupCopper_Hard,
            'enmParamType_CupSilver_Hard' => self::enmParamType_CupSilver_Hard,
            'enmParamType_CupGold_Hard' => self::enmParamType_CupGold_Hard,
            'enmParamType_CupPlatinum_Hard' => self::enmParamType_CupPlatinum_Hard,
            'enmParamType_CupCopper_GamePlay' => self::enmParamType_CupCopper_GamePlay,
            'enmParamType_CupSilver_GamePlay' => self::enmParamType_CupSilver_GamePlay,
            'enmParamType_CupGold_GamePlay' => self::enmParamType_CupGold_GamePlay,
            'enmParamType_CupPlatinum_GamePlay' => self::enmParamType_CupPlatinum_GamePlay,
            'enmParamType_CupSilver' => self::enmParamType_CupSilver,
            'enmParamType_CupGold' => self::enmParamType_CupGold,
            'enmParamType_CupPlatinum' => self::enmParamType_CupPlatinum,
            'enmParamType_Qualify_Title' => self::enmParamType_Qualify_Title,
            'enmParamType_Qualify_Title_Rank2' => self::enmParamType_Qualify_Title_Rank2,
            'enmParamType_Qualify_Title_Rank3' => self::enmParamType_Qualify_Title_Rank3,
            'enmParamType_Qualify_Title_Rank4' => self::enmParamType_Qualify_Title_Rank4,
            'enmParamType_Qualify_Title_Rank5' => self::enmParamType_Qualify_Title_Rank5,
            'enmParamType_Qualify_Title_Rank03' => self::enmParamType_Qualify_Title_Rank03,
            'enmParamType_Qualify_Title_Rank13' => self::enmParamType_Qualify_Title_Rank13,
            'enmParamType_Qualify_Title_Rank23' => self::enmParamType_Qualify_Title_Rank23,
            'enmParamType_Follow_Count' => self::enmParamType_Follow_Count,
            'enmParamType_FansCount' => self::enmParamType_FansCount,
            'enmParamType_Friend_Count' => self::enmParamType_Friend_Count,
            'enmParamType_Friend_Favorability' => self::enmParamType_Friend_Favorability,
            'enmParamType_SendFriend' => self::enmParamType_SendFriend,
            'enmParamType_SendGift' => self::enmParamType_SendGift,
            'enmParamType_ReceiveGift' => self::enmParamType_ReceiveGift,
            'enmParamType_SendFameTotal' => self::enmParamType_SendFameTotal,
            'enmParamType_VisitHomePage' => self::enmParamType_VisitHomePage,
            'enmParamType_LikeHomePage' => self::enmParamType_LikeHomePage,
            'enmParamType_BeLikeHomePage' => self::enmParamType_BeLikeHomePage,
            'enmParamType_BigSpeaker' => self::enmParamType_BigSpeaker,
            'enmParamType_InSNSRoom_Enter' => self::enmParamType_InSNSRoom_Enter,
            'enmParamType_InSNSRoom_Time' => self::enmParamType_InSNSRoom_Time,
            'enmParamType_SNSRoom_NPC' => self::enmParamType_SNSRoom_NPC,
            'enmParamType_SNSRoom_Game' => self::enmParamType_SNSRoom_Game,
            'enmParamType_SNSRoom_Ball' => self::enmParamType_SNSRoom_Ball,
            'enmParamType_SNSRoom_Blind' => self::enmParamType_SNSRoom_Blind,
            'enmParamType_SNSRoom_Exchange' => self::enmParamType_SNSRoom_Exchange,
            'enmParamType_SNSRoom_Play' => self::enmParamType_SNSRoom_Play,
            'enmParamType_SNSRoom_PlayWheel' => self::enmParamType_SNSRoom_PlayWheel,
            'enmParamType_SNSRoom_PlayBoat' => self::enmParamType_SNSRoom_PlayBoat,
            'enmParamType_Meet' => self::enmParamType_Meet,
            'enmParamType_Confession' => self::enmParamType_Confession,
            'enmParamType_Lover' => self::enmParamType_Lover,
            'enmParamType_LoverToken' => self::enmParamType_LoverToken,
            'enmParamType_SNSRoom_Experence' => self::enmParamType_SNSRoom_Experence,
            'enmParamType_InSNSRoom_SwimPool' => self::enmParamType_InSNSRoom_SwimPool,
            'enmParamType_InSNSRoom_Drink' => self::enmParamType_InSNSRoom_Drink,
            'enmParamType_InSNSRoom_SwimPool_Time' => self::enmParamType_InSNSRoom_SwimPool_Time,
            'enmParamType_House_EnterMyHouse' => self::enmParamType_House_EnterMyHouse,
            'enmParamType_House_Level' => self::enmParamType_House_Level,
            'enmParamType_House_Level_3' => self::enmParamType_House_Level_3,
            'enmParamType_House_GetExperence' => self::enmParamType_House_GetExperence,
            'enmParamType_House_Dress_Count' => self::enmParamType_House_Dress_Count,
            'enmParamType_House_Luxury' => self::enmParamType_House_Luxury,
            'enmParamType_House_Dress' => self::enmParamType_House_Dress,
            'enmParamType_House_Make' => self::enmParamType_House_Make,
            'enmParamType_House_Buy_Furniture' => self::enmParamType_House_Buy_Furniture,
            'enmParamType_House_EnterZone' => self::enmParamType_House_EnterZone,
            'enmParamType_House_DressZone' => self::enmParamType_House_DressZone,
            'enmParamType_House_DressItem' => self::enmParamType_House_DressItem,
            'enmParamType_House_LuxuryZone' => self::enmParamType_House_LuxuryZone,
            'enmParamType_House_CreateRoom' => self::enmParamType_House_CreateRoom,
            'enmParamType_House_Dance' => self::enmParamType_House_Dance,
            'enmParamType_House_Invite' => self::enmParamType_House_Invite,
            'enmParamType_House_Visit' => self::enmParamType_House_Visit,
            'enmParamType_House_Like' => self::enmParamType_House_Like,
            'enmParamType_House_BeLike' => self::enmParamType_House_BeLike,
            'enmParamType_House_Merge' => self::enmParamType_House_Merge,
            'enmParamType_House_Merge_Lv' => self::enmParamType_House_Merge_Lv,
            'enmParamType_House_Produce' => self::enmParamType_House_Produce,
            'enmParamType_House_Stamina_Cost' => self::enmParamType_House_Stamina_Cost,
            'enmParamType_House_Stamina_Add' => self::enmParamType_House_Stamina_Add,
            'enmParamType_House_Task_Daily' => self::enmParamType_House_Task_Daily,
            'enmParamType_House_Merge_Level7' => self::enmParamType_House_Merge_Level7,
            'enmParamType_House_Merge_Level10' => self::enmParamType_House_Merge_Level10,
            'enmParamType_LoginCnt' => self::enmParamType_LoginCnt,
            'enmParamType_LoginMonth' => self::enmParamType_LoginMonth,
            'enmParamType_OnlineTime' => self::enmParamType_OnlineTime,
            'enmParamType_TodayTimePeriod_12_14' => self::enmParamType_TodayTimePeriod_12_14,
            'enmParamType_TodayTimePeriod_19_21' => self::enmParamType_TodayTimePeriod_19_21,
            'enmParamType_SignCnt' => self::enmParamType_SignCnt,
            'enmParamType_Challenge_Pass' => self::enmParamType_Challenge_Pass,
            'enmParamType_JigsawPuzzle' => self::enmParamType_JigsawPuzzle,
            'enmParamType_FireWorksWish' => self::enmParamType_FireWorksWish,
            'enmParamType_FireWorksBeLiked' => self::enmParamType_FireWorksBeLiked,
            'enmParamType_WishFree' => self::enmParamType_WishFree,
            'enmParamType_WishBuyBoxCount' => self::enmParamType_WishBuyBoxCount,
            'enmParamType_BPActive' => self::enmParamType_BPActive,
            'enmParamType_BPLevel' => self::enmParamType_BPLevel,
            'enmParamType_BPPayment' => self::enmParamType_BPPayment,
            'enmParamType_MergeLineSection' => self::enmParamType_MergeLineSection,
            'enmParamType_DanceDropGet' => self::enmParamType_DanceDropGet,
            'enmParamType_UseItem6035' => self::enmParamType_UseItem6035,
            'enmParamType_GetItem10111' => self::enmParamType_GetItem10111,
            'enmParamType_GetItem1' => self::enmParamType_GetItem1,
            'enmParamType_GetItem2' => self::enmParamType_GetItem2,
            'enmParamType_GetItem3' => self::enmParamType_GetItem3,
            'enmParamType_GetItem4' => self::enmParamType_GetItem4,
            'enmParamType_GetItem5' => self::enmParamType_GetItem5,
            'enmParamType_GetItem6' => self::enmParamType_GetItem6,
            'enmParamType_GetItem7' => self::enmParamType_GetItem7,
            'enmParamType_GetItem8' => self::enmParamType_GetItem8,
            'enmParamType_WishBuy' => self::enmParamType_WishBuy,
            'enmParamType_WishUseTotal' => self::enmParamType_WishUseTotal,
            'enmParamType_BuySecretBox' => self::enmParamType_BuySecretBox,
            'enmParamType_LoginCntAfterBuyBox' => self::enmParamType_LoginCntAfterBuyBox,
            'enmParamType_GetItem6034' => self::enmParamType_GetItem6034,
            'enmParamType_Couple_Be' => self::enmParamType_Couple_Be,
            'enmParamType_Couple_Camera' => self::enmParamType_Couple_Camera,
            'enmParamType_Couple_Ferris' => self::enmParamType_Couple_Ferris,
            'enmParamType_Couple_Yacht' => self::enmParamType_Couple_Yacht,
            'enmParamType_Couple_Medal' => self::enmParamType_Couple_Medal,
            'enmParamType_Couple_Raise' => self::enmParamType_Couple_Raise,
            'enmParamType_Couple_Chat' => self::enmParamType_Couple_Chat,
            'enmParamType_HonourAcc' => self::enmParamType_HonourAcc,
            'enmParamType_DanceDropBall_SSS' => self::enmParamType_DanceDropBall_SSS,
            'enmParamType_DanceHeartStar_SSS' => self::enmParamType_DanceHeartStar_SSS,
        );
    }
}
}