<?php
/**
 * Auto generated from define.proto at 2023-02-13 12:39:22
 */

namespace Xnhd\Core\Pb\Sdo {
/**
 * SourceChannel enum
 */
final class SourceChannel
{
    const enmSourceChannel_Mask = 268369920;
    const enmSourceChannel_None = 0;
    const enmSourceChannel_Pay = 65536;
    const enmSourceChannel_Pay_GM = 65537;
    const enmSourceChannel_Pay_Month = 65792;
    const enmSourceChannel_Pay_Month_GM = 65793;
    const enmSourceChannel_Pay_MonthUlti = 65808;
    const enmSourceChannel_Pay_MonthUlti_GM = 65809;
    const enmSourceChannel_Pay_CrownMonth = 66048;
    const enmSourceChannel_Pay_CrownMonth_GM = 66049;
    const enmSourceChannel_Pay_CrownYear = 66064;
    const enmSourceChannel_Pay_CrownYear_GM = 66065;
    const enmSourceChannel_Pay_BattlePass = 66304;
    const enmSourceChannel_Pay_OneYuan = 67328;
    const enmSourceChannel_Pay_NYuan = 67344;
    const enmSourceChannel_Pay_Fund = 86019;
    const enmSourceChannel_Pay_CoupleBP = 86020;
    const enmSourceChannel_Pay_Unknow = 126976;
    const enmSourceChannel_FileReview_HeadPic = 1048577;
    const enmSourceChannel_FileReview_AlbumPic = 1048578;
    const enmSourceChannel_FileReview_Voice = 1048579;
    const enmSourceChannel_FileReview_CoupleDiaryPic = 1048580;
    const enmSourceChannel_FileReview_BeckPic = 1048581;
    const enmSourceChannel_CreateRole = 2162688;
    const enmSourceChannel_OpenModule = 2162689;
    const enmSourceChannel_FreshPrize = 2162690;
    const enmSourceChannel_Rebate = 2162691;
    const enmSourceChannel_Mall_Normal = 2228224;
    const enmSourceChannel_Mall_Theme = 2228225;
    const enmSourceChannel_Mall_Couple = 2228226;
    const enmSourceChannel_Mall_SNS = 2228227;
    const enmSourceChannel_Mall_Qualify = 2228228;
    const enmSourceChannel_Mall_Guild = 2228229;
    const enmSourceChannel_Mall_Raffle = 2228230;
    const enmSourceChannel_Mall_Treasure = 2228231;
    const enmSourceChannel_Mall_House = 2228232;
    const enmSourceChannel_Mall_Wedding = 2228233;
    const enmSourceChannel_Mall_WeddingGift = 2228234;
    const enmSourceChannel_Mall_SwimPool = 2228235;
    const enmSourceChannel_Mall_Furniture = 2228236;
    const enmSourceChannel_Mall_SwimCloth = 2228237;
    const enmSourceChannel_Mall_FreshGoods = 2228238;
    const enmSourceChannel_Mall_FreshGiftBox = 2228239;
    const enmSourceChannel_Mall_StarCall = 2228240;
    const enmSourceChannel_Mall_StarCall_2 = 2228241;
    const enmSourceChannel_Mall_ConsumScore = 2228242;
    const enmSourceChannel_Mall_Activty = 2228243;
    const enmSourceChannel_Send = 2232336;
    const enmSourceChannel_AskFor = 2232337;
    const enmSourceChannel_Refresh = 2232352;
    const enmSourceChannel_BuyStamina = 2232368;
    const enmSourceChannel_BuyGCoin = 2232384;
    const enmSourceChannel_MulBuyGCoin = 2232385;
    const enmSourceChannel_AutoAddStamina = 2232386;
    const enmSourceChannel_BuyFruit = 2232387;
    const enmSourceChannel_BuyStone2 = 2232388;
    const enmSourceChannel_Sale = 2293763;
    const enmSourceChannel_Decom = 2293764;
    const enmSourceChannel_Compose = 2293765;
    const enmSourceChannel_Extract = 2293766;
    const enmSourceChannel_Advance = 2293767;
    const enmSourceChannel_Item_TimeOut = 2359296;
    const enmSourceChannel_Item_Make = 2359297;
    const enmSourceChannel_Item_Color = 2359298;
    const enmSourceChannel_Item_Advance = 2359299;
    const enmSourceChannel_Item_Restore = 2359300;
    const enmSourceChannel_Item_PutOnBoard = 2359301;
    const enmSourceChannel_Item_TakeOutBoard = 2359302;
    const enmSourceChannel_Item_ClearCD = 2359303;
    const enmSourceChannel_Item_OpenBoxSlot = 2359304;
    const enmSourceChannel_Item_Produce = 2359305;
    const enmSourceChannel_Item_ItemBook = 2359306;
    const enmSourceChannel_Item_Exchange = 2359307;
    const enmSourceChannel_Item_LevelUp = 2359313;
    const enmSourceChannel_Item_RankUp = 2359314;
    const enmSourceChannel_UseItem = 2424832;
    const enmSourceChannel_ByTime = 2424833;
    const enmSourceChannel_SuitPrize = 2424834;
    const enmSourceChannel_RentItem = 2424835;
    const enmSourceChannel_ZoneMoneyRedBag = 2424836;
    const enmSourceChannel_ZoneScoreRedBag = 2424837;
    const enmSourceChannel_ZoneGCoinRedBag = 2424838;
    const enmSourceChannel_RoomScoreRedBag = 2424839;
    const enmSourceChannel_RoomGCoinRedBag = 2424840;
    const enmSourceChannel_GuildScoreRedBag = 2424841;
    const enmSourceChannel_GuildGCoinRedBag = 2424842;
    const enmSourceChannel_CatchRedBag = 2424843;
    const enmSourceChannel_Transfer = 2424844;
    const enmSourceChannel_Mail = 2490368;
    const enmSourceChannel_Mail_Invite = 2490369;
    const enmSourceChannel_Mail_Like = 2490370;
    const enmSourceChannel_Mail_Share = 2490371;
    const enmSourceChannel_Wedding = 2555904;
    const enmSourceChannel_Wedding_Renew = 2555905;
    const enmSourceChannel_Wedding_RoomBuffer = 2555906;
    const enmSourceChannel_Wedding_Rain = 2555907;
    const enmSourceChannel_Wedding_Game = 2555908;
    const enmSourceChannel_Skill_Learn = 2621441;
    const enmSourceChannel_VIP = 2686977;
    const enmSourceChannel_PayBonus = 2686978;
    const enmSourceChannel_Return = 2686979;
    const enmSourceChannel_BindXiNiu = 2686980;
    const enmSourceChannel_XiNiuPayBonus = 2686981;
    const enmSourceChannel_BindQQ = 2686982;
    const enmSourceChannel_Crown = 2686983;
    const enmSourceChannel_Anchor_Gift = 2752513;
    const enmSourceChannel_Anchor_Puzzle = 2752514;
    const enmSourceChannel_Anchor_Prize = 2752515;
    const enmSourceChannel_Auction_Sale = 2818049;
    const enmSourceChannel_Auction_Storage = 2818050;
    const enmSourceChannel_Auction_Bid = 2818051;
    const enmSourceChannel_Auction_Return = 2818052;
    const enmSourceChannel_CreateRoom = 3211265;
    const enmSourceChannel_Album = 3211266;
    const enmSourceChannel_Match_Amateur_1v1 = 3211267;
    const enmSourceChannel_Match_Amateur_2v2 = 3211268;
    const enmSourceChannel_Match_Qualify_1v1 = 3211269;
    const enmSourceChannel_Match_Qualify_2v2 = 3211270;
    const enmSourceChannel_Match_Idol = 3211271;
    const enmSourceChannel_Match_Challenge = 3211272;
    const enmSourceChannel_BossPK = 3211273;
    const enmSourceChannel_KikiGame = 3211274;
    const enmSourceChannel_Match_Task = 3211275;
    const enmSourceChannel_Match_Activity = 3211276;
    const enmSourceChannel_Match_GuildPK = 3211277;
    const enmSourceChannel_House = 3211278;
    const enmSourceChannel_Match_Video = 3211518;
    const enmSourceChannel_Auto_CreateRoom = 3211519;
    const enmSourceChannel_Flop = 3276802;
    const enmSourceChannel_Leisure_Buffer = 3276803;
    const enmSourceChannel_Leisure_Chest = 3276804;
    const enmSourceChannel_Leisure_Drink = 3276805;
    const enmSourceChannel_Leisure_Talk = 3276806;
    const enmSourceChannel_Leisure_SendGift = 3276807;
    const enmSourceChannel_Leisure_BallGame = 3276808;
    const enmSourceChannel_Leisure_Boat_Small = 3280897;
    const enmSourceChannel_Leisure_Boat_Big = 3280898;
    const enmSourceChannel_Leisure_Boat_Match = 3280899;
    const enmSourceChannel_Leisure_Wheel_Normal = 3281153;
    const enmSourceChannel_Leisure_Wheel_Match = 3281154;
    const enmSourceChannel_Leisure_Airship = 3281409;
    const enmSourceChannel_Leisure_SceneDesk = 3281665;
    const enmSourceChannel_Leisure_GuildRoom = 3281921;
    const enmSourceChannel_Leisure_All = 3280896;
    const enmSourceChannel_Raffle_SNS = 4259840;
    const enmSourceChannel_Raffle_Treasure = 4325376;
    const enmSourceChannel_Raffle_BoxPray = 4390912;
    const enmSourceChannel_Raffle_StarCall = 4456448;
    const enmSourceChannel_Quest_Advent = 458752;
    const enmSourceChannel_Quest_Grow = 458753;
    const enmSourceChannel_Quest_Daily = 458754;
    const enmSourceChannel_Quest_Achieve = 458755;
    const enmSourceChannel_Quest_RecvTask = 458756;
    const enmSourceChannel_Quest_Guild = 458757;
    const enmSourceChannel_Quest_Love = 458758;
    const enmSourceChannel_Quest_Circle = 458759;
    const enmSourceChannel_Quest_Advent2 = 458760;
    const enmSourceChannel_Activity = 524288;
    const enmSourceChannel_Act_ActiveDay_Task = 524313;
    const enmSourceChannel_Act_NewPlayerTran_Prize = 524369;
    const enmSourceChannel_Act_LimitGift = 524384;
    const enmSourceChannel_Act_Exchange = 524318;
    const enmSourceChannel_Act_Invite_InviteBind = 524545;
    const enmSourceChannel_Act_Invite_InviteInstal = 524546;
    const enmSourceChannel_Act_Invite_InviteReturn = 524547;
    const enmSourceChannel_Act_Invite_InvitePay = 524548;
    const enmSourceChannel_Act_Invite_ReturnLogin = 524549;
    const enmSourceChannel_Act_Invite_ReturnPay = 524550;
    const enmSourceChannel_Act_Invite_ReturnDance = 524551;
    const enmSourceChannel_Act_Raffle_Exchange = 524801;
    const enmSourceChannel_Act_Raffle_Mouse = 524802;
    const enmSourceChannel_Act_Raffle_Card_9 = 524803;
    const enmSourceChannel_Act_Raffle_Card_12 = 524804;
    const enmSourceChannel_Act_Raffle_Card_16 = 524805;
    const enmSourceChannel_Act_NewPlayer_Day1 = 525057;
    const enmSourceChannel_Act_NewPlayer_Day2 = 525058;
    const enmSourceChannel_Act_NewPlayer_Day3 = 525059;
    const enmSourceChannel_Act_NewPlayer_Day4 = 525060;
    const enmSourceChannel_Act_NewPlayer_Day5 = 525061;
    const enmSourceChannel_Act_NewPlayer_Day6 = 525062;
    const enmSourceChannel_Act_NewPlayer_Day7 = 525063;
    const enmSourceChannel_Act_NewPlayer_Day8 = 525064;
    const enmSourceChannel_Act_QA = 526081;
    const enmSourceChannel_Act_WeekDance = 526337;
    const enmSourceChannel_Act_LuckyPay = 526593;
    const enmSourceChannel_Act_TimeLimitBox_Task = 526849;
    const enmSourceChannel_Act_TimeLimitBox_Online = 526850;
    const enmSourceChannel_Act_DailyWelPay = 527617;
    const enmSourceChannel_Act_WelPay = 527873;
    const enmSourceChannel_Act_Rank = 528129;
    const enmSourceChannel_Act_BP_COMMON = 525890;
    const enmSourceChannel_Act_BP_PAYMENT = 525891;
    const enmSourceChannel_Act_BP_TASK1 = 525892;
    const enmSourceChannel_Act_BP_TASK2 = 525893;
    const enmSourceChannel_Act_BP_TASK3 = 525894;
    const enmSourceChannel_Act_BP_TASK4 = 525895;
    const enmSourceChannel_Act_BP_TASK5 = 525896;
    const enmSourceChannel_Act_BP_EXCHANGE = 525897;
    const enmSourceChannel_Act_BP_ACTIVE = 525898;
    const enmSourceChannel_Act_BP_PURCHASE = 525899;
    const enmSourceChannel_Act_BP_PURCHASELEVEL = 525900;
    const enmSourceChannel_Act_Puzzle = 525989;
    const enmSourceChannel_Act_Puzzle_Box = 525993;
    const enmSourceChannel_Act_MileStone = 528144;
    const enmSourceChannel_Act_PPGame = 526393;
    const enmSourceChannel_Act_FirstPay = 526288;
    const enmSourceChannel_Act_MonthCard = 526289;
    const enmSourceChannel_Act_ExchangeKey = 526290;
    const enmSourceChannel_Act_MergeLine = 526588;
    const enmSourceChannel_Act_Treasure = 526598;
    const enmSourceChannel_Act_DirectPurchase = 526618;
    const enmAssetChannelID_Chat_Default = 589824;
    const enmAssetChannelID_Chat_WeddingMC = 589825;
    const enmAssetChannelID_Chat_Big = 589826;
    const enmAssetChannelID_Chat_LoverBigSpk = 589827;
    const enmAssetChannelID_Chat_CrossZone = 589828;
    const enmAssetChannelID_Chat_LoverSmallSpk = 589829;
    const enmAssetChannelID_Chat_Small = 589830;
    const enmAssetChannelID_Chat_Ultimate = 589831;
    const enmAssetChannelID_Chat_EffectCard = 589832;
    const enmSourceChannel_Guild_Create = 327681;
    const enmSourceChannel_Role_Donate = 327682;
    const enmSourceChannel_Guild_ChangeName = 327683;
    const enmSourceChannel_Guild_RefreshGuildTask = 327684;
    const enmSourceChannel_Guild_ForceCompleteGuildTask = 327685;
    const enmSourceChannel_Guild_CompleteGuildTask = 327686;
    const enmSourceChannel_Guild_PlayWithGuardian = 327687;
    const enmSourceChannel_Guild_Worship = 327688;
    const enmSourceChannel_Guild_GetWorshipPrize = 327689;
    const enmSourceChannel_Guild_ActiveTask = 327696;
    const enmSourceChannel_Guild_UnlockStage = 327697;
    const enmSourceChannel_Guild_CreateConcert = 327698;
    const enmSourceChannel_Guild_QuickAccomplishConcert = 327699;
    const enmSourceChannel_Guild_Sign = 327700;
    const enmSourceChannel_Guild_HonourReward = 327701;
    const enmSourceChannel_Guild_Rename = 327702;
    const enmSourceChannel_Guild_Enter = 327703;
    const enmSourceChannel_Guild_Exit = 327704;
    const enmSourceChannel_Guild_Recruit = 327705;
    const enmSourceChannel_Guild_Dissolve = 327706;
    const enmSourceChannel_Guild_LevelUp = 327707;
    const enmSourceChannel_Qualify = 655360;
    const enmSourceChannel_Qualify_RankPrize = 655361;
    const enmSourceChannel_Qualify_CareerPrize = 655362;
    const enmSourceChannel_Qualify_SeasonPrize = 655363;
    const enmSourceChannel_Relation_LoverValue_Dance = 720901;
    const enmSourceChannel_Relation_LoverValue_MissRedBean = 720902;
    const enmSourceChannel_Relation_LoverValue_ActionCard = 720903;
    const enmSourceChannel_Relation_LoverValue_LoverDiamond = 720904;
    const enmSourceChannel_Relation_LoverValue_LoverSpeaker = 720905;
    const enmSourceChannel_Relation_Intimacy_Dance = 720917;
    const enmSourceChannel_Relation_Intimacy_ActionCard = 720918;
    const enmSourceChannel_Relation_Intimacy_SendFlowers = 720919;
    const enmSourceChannel_Relation_Intimacy_SendGifts = 720920;
    const enmSourceChannel_Relation_Intimacy_SendFCoin = 720921;
    const enmSourceChannel_Relation_WearKeepsake = 786433;
    const enmSourceChannel_Relation_Confess = 786434;
    const enmSourceChannel_Relation_SendGift = 786435;
    const enmSourceChannel_Relation_RecvFCoin = 786436;
    const enmSourceChannel_Relation_Breakup = 786437;
    const enmSourceChannel_Relation_Recover = 786438;
    const enmSourceChannel_Relation_AddFriend_Friend = 790529;
    const enmSourceChannel_Relation_AddFriend_Chat = 790530;
    const enmSourceChannel_Relation_AddFriend_Entertainment = 790531;
    const enmSourceChannel_Relation_AddFriend_FateTree = 790532;
    const enmSourceChannel_Relation_AddFriend_Rank = 790533;
    const enmSourceChannel_Relation_AddFriend_Guild = 790534;
    const enmSourceChannel_Relation_AddFriend_WaittingRoom = 790535;
    const enmSourceChannel_Relation_AddFriend_PersonalData = 790536;
    const enmSourceChannel_Relation_AddFriend_Other = 790537;
    const enmSourceChannel_Relation_Couple_Medal_Prize = 790538;
    const enmSourceChannel_Relation_Woo = 794624;
    const enmSourceChannel_Relation_Plan = 798720;
    const enmSourceChannel_Relation_PlanTask = 798721;
    const enmSourceChannel_Relation_RaiseLevel = 798722;
    const enmSourceChannel_Relation_CPDancePrize = 798723;
    const enmSourceChannel_Task_MainTask = 851969;
    const enmSourceChannel_Task_ResetTask = 851970;
    const enmSourceChannel_Task_LoverTask = 851971;
    const enmSourceChannel_Task_AccelerateTask = 851972;
    const enmSourceChannel_Album_Work = 856065;
    const enmSourceChannel_Album_Prize = 856066;
    const enmSourceChannel_Album_AddTimes = 856067;
    const enmSourceChannel_Garden_Sow = 860161;
    const enmSourceChannel_Garden_Reap = 860162;
    const enmSourceChannel_Garden_SpeedUp = 860163;
    const enmSourceChannel_Garden_AddPot = 860164;
    const enmSourceChannel_Garden_Water = 860165;
    const enmSourceChannel_Achieve_Prize = 856080;
    const enmSourceChannel_GM = 167772160;
    const enmSourceChannel_TestPrize = 167772161;
    const enmSourceChannel_TestExtraPrize = 167772162;
    const enmSourceChannel_GM_Exchange = 167772163;
    const enmSourceChannel_Tour = 864257;
    const enmSourceChannel_Tour_Puzzle = 864258;
    const enmSourceChannel_Tour_Section = 864259;
    const enmSourceChannel_Tour_Tree = 864260;
    const enmSourceChannel_Tour_TreeKey = 864261;
    const enmSourceChannel_Tour_PuzzlePart = 864262;
    const enmSourceChannel_Wish_Gift = 868353;
    const enmSourceChannel_Wish_BOX = 868354;

    /**
     * Returns defined enum values
     *
     * @return int[]
     */
    public function getEnumValues()
    {
        return array(
            'enmSourceChannel_Mask' => self::enmSourceChannel_Mask,
            'enmSourceChannel_None' => self::enmSourceChannel_None,
            'enmSourceChannel_Pay' => self::enmSourceChannel_Pay,
            'enmSourceChannel_Pay_GM' => self::enmSourceChannel_Pay_GM,
            'enmSourceChannel_Pay_Month' => self::enmSourceChannel_Pay_Month,
            'enmSourceChannel_Pay_Month_GM' => self::enmSourceChannel_Pay_Month_GM,
            'enmSourceChannel_Pay_MonthUlti' => self::enmSourceChannel_Pay_MonthUlti,
            'enmSourceChannel_Pay_MonthUlti_GM' => self::enmSourceChannel_Pay_MonthUlti_GM,
            'enmSourceChannel_Pay_CrownMonth' => self::enmSourceChannel_Pay_CrownMonth,
            'enmSourceChannel_Pay_CrownMonth_GM' => self::enmSourceChannel_Pay_CrownMonth_GM,
            'enmSourceChannel_Pay_CrownYear' => self::enmSourceChannel_Pay_CrownYear,
            'enmSourceChannel_Pay_CrownYear_GM' => self::enmSourceChannel_Pay_CrownYear_GM,
            'enmSourceChannel_Pay_BattlePass' => self::enmSourceChannel_Pay_BattlePass,
            'enmSourceChannel_Pay_OneYuan' => self::enmSourceChannel_Pay_OneYuan,
            'enmSourceChannel_Pay_NYuan' => self::enmSourceChannel_Pay_NYuan,
            'enmSourceChannel_Pay_Fund' => self::enmSourceChannel_Pay_Fund,
            'enmSourceChannel_Pay_CoupleBP' => self::enmSourceChannel_Pay_CoupleBP,
            'enmSourceChannel_Pay_Unknow' => self::enmSourceChannel_Pay_Unknow,
            'enmSourceChannel_FileReview_HeadPic' => self::enmSourceChannel_FileReview_HeadPic,
            'enmSourceChannel_FileReview_AlbumPic' => self::enmSourceChannel_FileReview_AlbumPic,
            'enmSourceChannel_FileReview_Voice' => self::enmSourceChannel_FileReview_Voice,
            'enmSourceChannel_FileReview_CoupleDiaryPic' => self::enmSourceChannel_FileReview_CoupleDiaryPic,
            'enmSourceChannel_FileReview_BeckPic' => self::enmSourceChannel_FileReview_BeckPic,
            'enmSourceChannel_CreateRole' => self::enmSourceChannel_CreateRole,
            'enmSourceChannel_OpenModule' => self::enmSourceChannel_OpenModule,
            'enmSourceChannel_FreshPrize' => self::enmSourceChannel_FreshPrize,
            'enmSourceChannel_Rebate' => self::enmSourceChannel_Rebate,
            'enmSourceChannel_Mall_Normal' => self::enmSourceChannel_Mall_Normal,
            'enmSourceChannel_Mall_Theme' => self::enmSourceChannel_Mall_Theme,
            'enmSourceChannel_Mall_Couple' => self::enmSourceChannel_Mall_Couple,
            'enmSourceChannel_Mall_SNS' => self::enmSourceChannel_Mall_SNS,
            'enmSourceChannel_Mall_Qualify' => self::enmSourceChannel_Mall_Qualify,
            'enmSourceChannel_Mall_Guild' => self::enmSourceChannel_Mall_Guild,
            'enmSourceChannel_Mall_Raffle' => self::enmSourceChannel_Mall_Raffle,
            'enmSourceChannel_Mall_Treasure' => self::enmSourceChannel_Mall_Treasure,
            'enmSourceChannel_Mall_House' => self::enmSourceChannel_Mall_House,
            'enmSourceChannel_Mall_Wedding' => self::enmSourceChannel_Mall_Wedding,
            'enmSourceChannel_Mall_WeddingGift' => self::enmSourceChannel_Mall_WeddingGift,
            'enmSourceChannel_Mall_SwimPool' => self::enmSourceChannel_Mall_SwimPool,
            'enmSourceChannel_Mall_Furniture' => self::enmSourceChannel_Mall_Furniture,
            'enmSourceChannel_Mall_SwimCloth' => self::enmSourceChannel_Mall_SwimCloth,
            'enmSourceChannel_Mall_FreshGoods' => self::enmSourceChannel_Mall_FreshGoods,
            'enmSourceChannel_Mall_FreshGiftBox' => self::enmSourceChannel_Mall_FreshGiftBox,
            'enmSourceChannel_Mall_StarCall' => self::enmSourceChannel_Mall_StarCall,
            'enmSourceChannel_Mall_StarCall_2' => self::enmSourceChannel_Mall_StarCall_2,
            'enmSourceChannel_Mall_ConsumScore' => self::enmSourceChannel_Mall_ConsumScore,
            'enmSourceChannel_Mall_Activty' => self::enmSourceChannel_Mall_Activty,
            'enmSourceChannel_Send' => self::enmSourceChannel_Send,
            'enmSourceChannel_AskFor' => self::enmSourceChannel_AskFor,
            'enmSourceChannel_Refresh' => self::enmSourceChannel_Refresh,
            'enmSourceChannel_BuyStamina' => self::enmSourceChannel_BuyStamina,
            'enmSourceChannel_BuyGCoin' => self::enmSourceChannel_BuyGCoin,
            'enmSourceChannel_MulBuyGCoin' => self::enmSourceChannel_MulBuyGCoin,
            'enmSourceChannel_AutoAddStamina' => self::enmSourceChannel_AutoAddStamina,
            'enmSourceChannel_BuyFruit' => self::enmSourceChannel_BuyFruit,
            'enmSourceChannel_BuyStone2' => self::enmSourceChannel_BuyStone2,
            'enmSourceChannel_Sale' => self::enmSourceChannel_Sale,
            'enmSourceChannel_Decom' => self::enmSourceChannel_Decom,
            'enmSourceChannel_Compose' => self::enmSourceChannel_Compose,
            'enmSourceChannel_Extract' => self::enmSourceChannel_Extract,
            'enmSourceChannel_Advance' => self::enmSourceChannel_Advance,
            'enmSourceChannel_Item_TimeOut' => self::enmSourceChannel_Item_TimeOut,
            'enmSourceChannel_Item_Make' => self::enmSourceChannel_Item_Make,
            'enmSourceChannel_Item_Color' => self::enmSourceChannel_Item_Color,
            'enmSourceChannel_Item_Advance' => self::enmSourceChannel_Item_Advance,
            'enmSourceChannel_Item_Restore' => self::enmSourceChannel_Item_Restore,
            'enmSourceChannel_Item_PutOnBoard' => self::enmSourceChannel_Item_PutOnBoard,
            'enmSourceChannel_Item_TakeOutBoard' => self::enmSourceChannel_Item_TakeOutBoard,
            'enmSourceChannel_Item_ClearCD' => self::enmSourceChannel_Item_ClearCD,
            'enmSourceChannel_Item_OpenBoxSlot' => self::enmSourceChannel_Item_OpenBoxSlot,
            'enmSourceChannel_Item_Produce' => self::enmSourceChannel_Item_Produce,
            'enmSourceChannel_Item_ItemBook' => self::enmSourceChannel_Item_ItemBook,
            'enmSourceChannel_Item_Exchange' => self::enmSourceChannel_Item_Exchange,
            'enmSourceChannel_Item_LevelUp' => self::enmSourceChannel_Item_LevelUp,
            'enmSourceChannel_Item_RankUp' => self::enmSourceChannel_Item_RankUp,
            'enmSourceChannel_UseItem' => self::enmSourceChannel_UseItem,
            'enmSourceChannel_ByTime' => self::enmSourceChannel_ByTime,
            'enmSourceChannel_SuitPrize' => self::enmSourceChannel_SuitPrize,
            'enmSourceChannel_RentItem' => self::enmSourceChannel_RentItem,
            'enmSourceChannel_ZoneMoneyRedBag' => self::enmSourceChannel_ZoneMoneyRedBag,
            'enmSourceChannel_ZoneScoreRedBag' => self::enmSourceChannel_ZoneScoreRedBag,
            'enmSourceChannel_ZoneGCoinRedBag' => self::enmSourceChannel_ZoneGCoinRedBag,
            'enmSourceChannel_RoomScoreRedBag' => self::enmSourceChannel_RoomScoreRedBag,
            'enmSourceChannel_RoomGCoinRedBag' => self::enmSourceChannel_RoomGCoinRedBag,
            'enmSourceChannel_GuildScoreRedBag' => self::enmSourceChannel_GuildScoreRedBag,
            'enmSourceChannel_GuildGCoinRedBag' => self::enmSourceChannel_GuildGCoinRedBag,
            'enmSourceChannel_CatchRedBag' => self::enmSourceChannel_CatchRedBag,
            'enmSourceChannel_Transfer' => self::enmSourceChannel_Transfer,
            'enmSourceChannel_Mail' => self::enmSourceChannel_Mail,
            'enmSourceChannel_Mail_Invite' => self::enmSourceChannel_Mail_Invite,
            'enmSourceChannel_Mail_Like' => self::enmSourceChannel_Mail_Like,
            'enmSourceChannel_Mail_Share' => self::enmSourceChannel_Mail_Share,
            'enmSourceChannel_Wedding' => self::enmSourceChannel_Wedding,
            'enmSourceChannel_Wedding_Renew' => self::enmSourceChannel_Wedding_Renew,
            'enmSourceChannel_Wedding_RoomBuffer' => self::enmSourceChannel_Wedding_RoomBuffer,
            'enmSourceChannel_Wedding_Rain' => self::enmSourceChannel_Wedding_Rain,
            'enmSourceChannel_Wedding_Game' => self::enmSourceChannel_Wedding_Game,
            'enmSourceChannel_Skill_Learn' => self::enmSourceChannel_Skill_Learn,
            'enmSourceChannel_VIP' => self::enmSourceChannel_VIP,
            'enmSourceChannel_PayBonus' => self::enmSourceChannel_PayBonus,
            'enmSourceChannel_Return' => self::enmSourceChannel_Return,
            'enmSourceChannel_BindXiNiu' => self::enmSourceChannel_BindXiNiu,
            'enmSourceChannel_XiNiuPayBonus' => self::enmSourceChannel_XiNiuPayBonus,
            'enmSourceChannel_BindQQ' => self::enmSourceChannel_BindQQ,
            'enmSourceChannel_Crown' => self::enmSourceChannel_Crown,
            'enmSourceChannel_Anchor_Gift' => self::enmSourceChannel_Anchor_Gift,
            'enmSourceChannel_Anchor_Puzzle' => self::enmSourceChannel_Anchor_Puzzle,
            'enmSourceChannel_Anchor_Prize' => self::enmSourceChannel_Anchor_Prize,
            'enmSourceChannel_Auction_Sale' => self::enmSourceChannel_Auction_Sale,
            'enmSourceChannel_Auction_Storage' => self::enmSourceChannel_Auction_Storage,
            'enmSourceChannel_Auction_Bid' => self::enmSourceChannel_Auction_Bid,
            'enmSourceChannel_Auction_Return' => self::enmSourceChannel_Auction_Return,
            'enmSourceChannel_CreateRoom' => self::enmSourceChannel_CreateRoom,
            'enmSourceChannel_Album' => self::enmSourceChannel_Album,
            'enmSourceChannel_Match_Amateur_1v1' => self::enmSourceChannel_Match_Amateur_1v1,
            'enmSourceChannel_Match_Amateur_2v2' => self::enmSourceChannel_Match_Amateur_2v2,
            'enmSourceChannel_Match_Qualify_1v1' => self::enmSourceChannel_Match_Qualify_1v1,
            'enmSourceChannel_Match_Qualify_2v2' => self::enmSourceChannel_Match_Qualify_2v2,
            'enmSourceChannel_Match_Idol' => self::enmSourceChannel_Match_Idol,
            'enmSourceChannel_Match_Challenge' => self::enmSourceChannel_Match_Challenge,
            'enmSourceChannel_BossPK' => self::enmSourceChannel_BossPK,
            'enmSourceChannel_KikiGame' => self::enmSourceChannel_KikiGame,
            'enmSourceChannel_Match_Task' => self::enmSourceChannel_Match_Task,
            'enmSourceChannel_Match_Activity' => self::enmSourceChannel_Match_Activity,
            'enmSourceChannel_Match_GuildPK' => self::enmSourceChannel_Match_GuildPK,
            'enmSourceChannel_House' => self::enmSourceChannel_House,
            'enmSourceChannel_Match_Video' => self::enmSourceChannel_Match_Video,
            'enmSourceChannel_Auto_CreateRoom' => self::enmSourceChannel_Auto_CreateRoom,
            'enmSourceChannel_Flop' => self::enmSourceChannel_Flop,
            'enmSourceChannel_Leisure_Buffer' => self::enmSourceChannel_Leisure_Buffer,
            'enmSourceChannel_Leisure_Chest' => self::enmSourceChannel_Leisure_Chest,
            'enmSourceChannel_Leisure_Drink' => self::enmSourceChannel_Leisure_Drink,
            'enmSourceChannel_Leisure_Talk' => self::enmSourceChannel_Leisure_Talk,
            'enmSourceChannel_Leisure_SendGift' => self::enmSourceChannel_Leisure_SendGift,
            'enmSourceChannel_Leisure_BallGame' => self::enmSourceChannel_Leisure_BallGame,
            'enmSourceChannel_Leisure_Boat_Small' => self::enmSourceChannel_Leisure_Boat_Small,
            'enmSourceChannel_Leisure_Boat_Big' => self::enmSourceChannel_Leisure_Boat_Big,
            'enmSourceChannel_Leisure_Boat_Match' => self::enmSourceChannel_Leisure_Boat_Match,
            'enmSourceChannel_Leisure_Wheel_Normal' => self::enmSourceChannel_Leisure_Wheel_Normal,
            'enmSourceChannel_Leisure_Wheel_Match' => self::enmSourceChannel_Leisure_Wheel_Match,
            'enmSourceChannel_Leisure_Airship' => self::enmSourceChannel_Leisure_Airship,
            'enmSourceChannel_Leisure_SceneDesk' => self::enmSourceChannel_Leisure_SceneDesk,
            'enmSourceChannel_Leisure_GuildRoom' => self::enmSourceChannel_Leisure_GuildRoom,
            'enmSourceChannel_Leisure_All' => self::enmSourceChannel_Leisure_All,
            'enmSourceChannel_Raffle_SNS' => self::enmSourceChannel_Raffle_SNS,
            'enmSourceChannel_Raffle_Treasure' => self::enmSourceChannel_Raffle_Treasure,
            'enmSourceChannel_Raffle_BoxPray' => self::enmSourceChannel_Raffle_BoxPray,
            'enmSourceChannel_Raffle_StarCall' => self::enmSourceChannel_Raffle_StarCall,
            'enmSourceChannel_Quest_Advent' => self::enmSourceChannel_Quest_Advent,
            'enmSourceChannel_Quest_Grow' => self::enmSourceChannel_Quest_Grow,
            'enmSourceChannel_Quest_Daily' => self::enmSourceChannel_Quest_Daily,
            'enmSourceChannel_Quest_Achieve' => self::enmSourceChannel_Quest_Achieve,
            'enmSourceChannel_Quest_RecvTask' => self::enmSourceChannel_Quest_RecvTask,
            'enmSourceChannel_Quest_Guild' => self::enmSourceChannel_Quest_Guild,
            'enmSourceChannel_Quest_Love' => self::enmSourceChannel_Quest_Love,
            'enmSourceChannel_Quest_Circle' => self::enmSourceChannel_Quest_Circle,
            'enmSourceChannel_Quest_Advent2' => self::enmSourceChannel_Quest_Advent2,
            'enmSourceChannel_Activity' => self::enmSourceChannel_Activity,
            'enmSourceChannel_Act_ActiveDay_Task' => self::enmSourceChannel_Act_ActiveDay_Task,
            'enmSourceChannel_Act_NewPlayerTran_Prize' => self::enmSourceChannel_Act_NewPlayerTran_Prize,
            'enmSourceChannel_Act_LimitGift' => self::enmSourceChannel_Act_LimitGift,
            'enmSourceChannel_Act_Exchange' => self::enmSourceChannel_Act_Exchange,
            'enmSourceChannel_Act_Invite_InviteBind' => self::enmSourceChannel_Act_Invite_InviteBind,
            'enmSourceChannel_Act_Invite_InviteInstal' => self::enmSourceChannel_Act_Invite_InviteInstal,
            'enmSourceChannel_Act_Invite_InviteReturn' => self::enmSourceChannel_Act_Invite_InviteReturn,
            'enmSourceChannel_Act_Invite_InvitePay' => self::enmSourceChannel_Act_Invite_InvitePay,
            'enmSourceChannel_Act_Invite_ReturnLogin' => self::enmSourceChannel_Act_Invite_ReturnLogin,
            'enmSourceChannel_Act_Invite_ReturnPay' => self::enmSourceChannel_Act_Invite_ReturnPay,
            'enmSourceChannel_Act_Invite_ReturnDance' => self::enmSourceChannel_Act_Invite_ReturnDance,
            'enmSourceChannel_Act_Raffle_Exchange' => self::enmSourceChannel_Act_Raffle_Exchange,
            'enmSourceChannel_Act_Raffle_Mouse' => self::enmSourceChannel_Act_Raffle_Mouse,
            'enmSourceChannel_Act_Raffle_Card_9' => self::enmSourceChannel_Act_Raffle_Card_9,
            'enmSourceChannel_Act_Raffle_Card_12' => self::enmSourceChannel_Act_Raffle_Card_12,
            'enmSourceChannel_Act_Raffle_Card_16' => self::enmSourceChannel_Act_Raffle_Card_16,
            'enmSourceChannel_Act_NewPlayer_Day1' => self::enmSourceChannel_Act_NewPlayer_Day1,
            'enmSourceChannel_Act_NewPlayer_Day2' => self::enmSourceChannel_Act_NewPlayer_Day2,
            'enmSourceChannel_Act_NewPlayer_Day3' => self::enmSourceChannel_Act_NewPlayer_Day3,
            'enmSourceChannel_Act_NewPlayer_Day4' => self::enmSourceChannel_Act_NewPlayer_Day4,
            'enmSourceChannel_Act_NewPlayer_Day5' => self::enmSourceChannel_Act_NewPlayer_Day5,
            'enmSourceChannel_Act_NewPlayer_Day6' => self::enmSourceChannel_Act_NewPlayer_Day6,
            'enmSourceChannel_Act_NewPlayer_Day7' => self::enmSourceChannel_Act_NewPlayer_Day7,
            'enmSourceChannel_Act_NewPlayer_Day8' => self::enmSourceChannel_Act_NewPlayer_Day8,
            'enmSourceChannel_Act_QA' => self::enmSourceChannel_Act_QA,
            'enmSourceChannel_Act_WeekDance' => self::enmSourceChannel_Act_WeekDance,
            'enmSourceChannel_Act_LuckyPay' => self::enmSourceChannel_Act_LuckyPay,
            'enmSourceChannel_Act_TimeLimitBox_Task' => self::enmSourceChannel_Act_TimeLimitBox_Task,
            'enmSourceChannel_Act_TimeLimitBox_Online' => self::enmSourceChannel_Act_TimeLimitBox_Online,
            'enmSourceChannel_Act_DailyWelPay' => self::enmSourceChannel_Act_DailyWelPay,
            'enmSourceChannel_Act_WelPay' => self::enmSourceChannel_Act_WelPay,
            'enmSourceChannel_Act_Rank' => self::enmSourceChannel_Act_Rank,
            'enmSourceChannel_Act_BP_COMMON' => self::enmSourceChannel_Act_BP_COMMON,
            'enmSourceChannel_Act_BP_PAYMENT' => self::enmSourceChannel_Act_BP_PAYMENT,
            'enmSourceChannel_Act_BP_TASK1' => self::enmSourceChannel_Act_BP_TASK1,
            'enmSourceChannel_Act_BP_TASK2' => self::enmSourceChannel_Act_BP_TASK2,
            'enmSourceChannel_Act_BP_TASK3' => self::enmSourceChannel_Act_BP_TASK3,
            'enmSourceChannel_Act_BP_TASK4' => self::enmSourceChannel_Act_BP_TASK4,
            'enmSourceChannel_Act_BP_TASK5' => self::enmSourceChannel_Act_BP_TASK5,
            'enmSourceChannel_Act_BP_EXCHANGE' => self::enmSourceChannel_Act_BP_EXCHANGE,
            'enmSourceChannel_Act_BP_ACTIVE' => self::enmSourceChannel_Act_BP_ACTIVE,
            'enmSourceChannel_Act_BP_PURCHASE' => self::enmSourceChannel_Act_BP_PURCHASE,
            'enmSourceChannel_Act_BP_PURCHASELEVEL' => self::enmSourceChannel_Act_BP_PURCHASELEVEL,
            'enmSourceChannel_Act_Puzzle' => self::enmSourceChannel_Act_Puzzle,
            'enmSourceChannel_Act_Puzzle_Box' => self::enmSourceChannel_Act_Puzzle_Box,
            'enmSourceChannel_Act_MileStone' => self::enmSourceChannel_Act_MileStone,
            'enmSourceChannel_Act_PPGame' => self::enmSourceChannel_Act_PPGame,
            'enmSourceChannel_Act_FirstPay' => self::enmSourceChannel_Act_FirstPay,
            'enmSourceChannel_Act_MonthCard' => self::enmSourceChannel_Act_MonthCard,
            'enmSourceChannel_Act_ExchangeKey' => self::enmSourceChannel_Act_ExchangeKey,
            'enmSourceChannel_Act_MergeLine' => self::enmSourceChannel_Act_MergeLine,
            'enmSourceChannel_Act_Treasure' => self::enmSourceChannel_Act_Treasure,
            'enmSourceChannel_Act_DirectPurchase' => self::enmSourceChannel_Act_DirectPurchase,
            'enmAssetChannelID_Chat_Default' => self::enmAssetChannelID_Chat_Default,
            'enmAssetChannelID_Chat_WeddingMC' => self::enmAssetChannelID_Chat_WeddingMC,
            'enmAssetChannelID_Chat_Big' => self::enmAssetChannelID_Chat_Big,
            'enmAssetChannelID_Chat_LoverBigSpk' => self::enmAssetChannelID_Chat_LoverBigSpk,
            'enmAssetChannelID_Chat_CrossZone' => self::enmAssetChannelID_Chat_CrossZone,
            'enmAssetChannelID_Chat_LoverSmallSpk' => self::enmAssetChannelID_Chat_LoverSmallSpk,
            'enmAssetChannelID_Chat_Small' => self::enmAssetChannelID_Chat_Small,
            'enmAssetChannelID_Chat_Ultimate' => self::enmAssetChannelID_Chat_Ultimate,
            'enmAssetChannelID_Chat_EffectCard' => self::enmAssetChannelID_Chat_EffectCard,
            'enmSourceChannel_Guild_Create' => self::enmSourceChannel_Guild_Create,
            'enmSourceChannel_Role_Donate' => self::enmSourceChannel_Role_Donate,
            'enmSourceChannel_Guild_ChangeName' => self::enmSourceChannel_Guild_ChangeName,
            'enmSourceChannel_Guild_RefreshGuildTask' => self::enmSourceChannel_Guild_RefreshGuildTask,
            'enmSourceChannel_Guild_ForceCompleteGuildTask' => self::enmSourceChannel_Guild_ForceCompleteGuildTask,
            'enmSourceChannel_Guild_CompleteGuildTask' => self::enmSourceChannel_Guild_CompleteGuildTask,
            'enmSourceChannel_Guild_PlayWithGuardian' => self::enmSourceChannel_Guild_PlayWithGuardian,
            'enmSourceChannel_Guild_Worship' => self::enmSourceChannel_Guild_Worship,
            'enmSourceChannel_Guild_GetWorshipPrize' => self::enmSourceChannel_Guild_GetWorshipPrize,
            'enmSourceChannel_Guild_ActiveTask' => self::enmSourceChannel_Guild_ActiveTask,
            'enmSourceChannel_Guild_UnlockStage' => self::enmSourceChannel_Guild_UnlockStage,
            'enmSourceChannel_Guild_CreateConcert' => self::enmSourceChannel_Guild_CreateConcert,
            'enmSourceChannel_Guild_QuickAccomplishConcert' => self::enmSourceChannel_Guild_QuickAccomplishConcert,
            'enmSourceChannel_Guild_Sign' => self::enmSourceChannel_Guild_Sign,
            'enmSourceChannel_Guild_HonourReward' => self::enmSourceChannel_Guild_HonourReward,
            'enmSourceChannel_Guild_Rename' => self::enmSourceChannel_Guild_Rename,
            'enmSourceChannel_Guild_Enter' => self::enmSourceChannel_Guild_Enter,
            'enmSourceChannel_Guild_Exit' => self::enmSourceChannel_Guild_Exit,
            'enmSourceChannel_Guild_Recruit' => self::enmSourceChannel_Guild_Recruit,
            'enmSourceChannel_Guild_Dissolve' => self::enmSourceChannel_Guild_Dissolve,
            'enmSourceChannel_Guild_LevelUp' => self::enmSourceChannel_Guild_LevelUp,
            'enmSourceChannel_Qualify' => self::enmSourceChannel_Qualify,
            'enmSourceChannel_Qualify_RankPrize' => self::enmSourceChannel_Qualify_RankPrize,
            'enmSourceChannel_Qualify_CareerPrize' => self::enmSourceChannel_Qualify_CareerPrize,
            'enmSourceChannel_Qualify_SeasonPrize' => self::enmSourceChannel_Qualify_SeasonPrize,
            'enmSourceChannel_Relation_LoverValue_Dance' => self::enmSourceChannel_Relation_LoverValue_Dance,
            'enmSourceChannel_Relation_LoverValue_MissRedBean' => self::enmSourceChannel_Relation_LoverValue_MissRedBean,
            'enmSourceChannel_Relation_LoverValue_ActionCard' => self::enmSourceChannel_Relation_LoverValue_ActionCard,
            'enmSourceChannel_Relation_LoverValue_LoverDiamond' => self::enmSourceChannel_Relation_LoverValue_LoverDiamond,
            'enmSourceChannel_Relation_LoverValue_LoverSpeaker' => self::enmSourceChannel_Relation_LoverValue_LoverSpeaker,
            'enmSourceChannel_Relation_Intimacy_Dance' => self::enmSourceChannel_Relation_Intimacy_Dance,
            'enmSourceChannel_Relation_Intimacy_ActionCard' => self::enmSourceChannel_Relation_Intimacy_ActionCard,
            'enmSourceChannel_Relation_Intimacy_SendFlowers' => self::enmSourceChannel_Relation_Intimacy_SendFlowers,
            'enmSourceChannel_Relation_Intimacy_SendGifts' => self::enmSourceChannel_Relation_Intimacy_SendGifts,
            'enmSourceChannel_Relation_Intimacy_SendFCoin' => self::enmSourceChannel_Relation_Intimacy_SendFCoin,
            'enmSourceChannel_Relation_WearKeepsake' => self::enmSourceChannel_Relation_WearKeepsake,
            'enmSourceChannel_Relation_Confess' => self::enmSourceChannel_Relation_Confess,
            'enmSourceChannel_Relation_SendGift' => self::enmSourceChannel_Relation_SendGift,
            'enmSourceChannel_Relation_RecvFCoin' => self::enmSourceChannel_Relation_RecvFCoin,
            'enmSourceChannel_Relation_Breakup' => self::enmSourceChannel_Relation_Breakup,
            'enmSourceChannel_Relation_Recover' => self::enmSourceChannel_Relation_Recover,
            'enmSourceChannel_Relation_AddFriend_Friend' => self::enmSourceChannel_Relation_AddFriend_Friend,
            'enmSourceChannel_Relation_AddFriend_Chat' => self::enmSourceChannel_Relation_AddFriend_Chat,
            'enmSourceChannel_Relation_AddFriend_Entertainment' => self::enmSourceChannel_Relation_AddFriend_Entertainment,
            'enmSourceChannel_Relation_AddFriend_FateTree' => self::enmSourceChannel_Relation_AddFriend_FateTree,
            'enmSourceChannel_Relation_AddFriend_Rank' => self::enmSourceChannel_Relation_AddFriend_Rank,
            'enmSourceChannel_Relation_AddFriend_Guild' => self::enmSourceChannel_Relation_AddFriend_Guild,
            'enmSourceChannel_Relation_AddFriend_WaittingRoom' => self::enmSourceChannel_Relation_AddFriend_WaittingRoom,
            'enmSourceChannel_Relation_AddFriend_PersonalData' => self::enmSourceChannel_Relation_AddFriend_PersonalData,
            'enmSourceChannel_Relation_AddFriend_Other' => self::enmSourceChannel_Relation_AddFriend_Other,
            'enmSourceChannel_Relation_Couple_Medal_Prize' => self::enmSourceChannel_Relation_Couple_Medal_Prize,
            'enmSourceChannel_Relation_Woo' => self::enmSourceChannel_Relation_Woo,
            'enmSourceChannel_Relation_Plan' => self::enmSourceChannel_Relation_Plan,
            'enmSourceChannel_Relation_PlanTask' => self::enmSourceChannel_Relation_PlanTask,
            'enmSourceChannel_Relation_RaiseLevel' => self::enmSourceChannel_Relation_RaiseLevel,
            'enmSourceChannel_Relation_CPDancePrize' => self::enmSourceChannel_Relation_CPDancePrize,
            'enmSourceChannel_Task_MainTask' => self::enmSourceChannel_Task_MainTask,
            'enmSourceChannel_Task_ResetTask' => self::enmSourceChannel_Task_ResetTask,
            'enmSourceChannel_Task_LoverTask' => self::enmSourceChannel_Task_LoverTask,
            'enmSourceChannel_Task_AccelerateTask' => self::enmSourceChannel_Task_AccelerateTask,
            'enmSourceChannel_Album_Work' => self::enmSourceChannel_Album_Work,
            'enmSourceChannel_Album_Prize' => self::enmSourceChannel_Album_Prize,
            'enmSourceChannel_Album_AddTimes' => self::enmSourceChannel_Album_AddTimes,
            'enmSourceChannel_Garden_Sow' => self::enmSourceChannel_Garden_Sow,
            'enmSourceChannel_Garden_Reap' => self::enmSourceChannel_Garden_Reap,
            'enmSourceChannel_Garden_SpeedUp' => self::enmSourceChannel_Garden_SpeedUp,
            'enmSourceChannel_Garden_AddPot' => self::enmSourceChannel_Garden_AddPot,
            'enmSourceChannel_Garden_Water' => self::enmSourceChannel_Garden_Water,
            'enmSourceChannel_Achieve_Prize' => self::enmSourceChannel_Achieve_Prize,
            'enmSourceChannel_GM' => self::enmSourceChannel_GM,
            'enmSourceChannel_TestPrize' => self::enmSourceChannel_TestPrize,
            'enmSourceChannel_TestExtraPrize' => self::enmSourceChannel_TestExtraPrize,
            'enmSourceChannel_GM_Exchange' => self::enmSourceChannel_GM_Exchange,
            'enmSourceChannel_Tour' => self::enmSourceChannel_Tour,
            'enmSourceChannel_Tour_Puzzle' => self::enmSourceChannel_Tour_Puzzle,
            'enmSourceChannel_Tour_Section' => self::enmSourceChannel_Tour_Section,
            'enmSourceChannel_Tour_Tree' => self::enmSourceChannel_Tour_Tree,
            'enmSourceChannel_Tour_TreeKey' => self::enmSourceChannel_Tour_TreeKey,
            'enmSourceChannel_Tour_PuzzlePart' => self::enmSourceChannel_Tour_PuzzlePart,
            'enmSourceChannel_Wish_Gift' => self::enmSourceChannel_Wish_Gift,
            'enmSourceChannel_Wish_BOX' => self::enmSourceChannel_Wish_BOX,
        );
    }
}
}